Repository GamedevExperienceStables/gamedev-experience-stables, pull requests merged in 2022-12, with the labels that each got.

#10 Update README.md
  README.md
Labels: DEV | refactoring

#23 Created empty project
  .gitignore
  Assets/Scenes.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scenes/SampleScene.unity.meta
  Assets/Settings.meta
  Assets/Settings/Input.meta
  Assets/Settings/Input/InputSystem.inputsettings.asset
  Assets/Settings/Input/InputSystem.inputsettings.asset.meta
  Assets/Settings/PostProcessing.meta
  Assets/Settings/PostProcessing/SampleSceneProfile.asset
  Assets/Settings/PostProcessing/SampleSceneProfile.asset.meta
  Assets/Settings/URP.meta
  Assets/Settings/URP/URP-Balanced-Renderer.asset
  Assets/Settings/URP/URP-Balanced-Renderer.asset.meta
  Assets/Settings/URP/URP-Balanced.asset
  Assets/Settings/URP/URP-Balanced.asset.meta
  Assets/Settings/URP/URP-HighFidelity-Renderer.asset
  Assets/Settings/URP/URP-HighFidelity-Renderer.asset.meta
  Assets/Settings/URP/URP-HighFidelity.asset
  Assets/Settings/URP/URP-HighFidelity.asset.meta
  Assets/Settings/URP/URP-Performant-Renderer.asset
  Assets/Settings/URP/URP-Performant-Renderer.asset.meta
  Assets/Settings/URP/URP-Performant.asset
  Assets/Settings/URP/URP-Performant.asset.meta
  Assets/UniversalRenderPipelineGlobalSettings.asset
  Assets/UniversalRenderPipelineGlobalSettings.asset.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/AudioManager.asset
  ProjectSettings/BurstAotSettings_StandaloneWindows.json
  ProjectSettings/ClusterInputManager.asset
  ProjectSettings/CommonBurstAotSettings.json
  ProjectSettings/DynamicsManager.asset
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/EditorSettings.asset
  ProjectSettings/GraphicsSettings.asset
  ProjectSettings/InputManager.asset
  ProjectSettings/MemorySettings.asset
  ProjectSettings/NavMeshAreas.asset
  ProjectSettings/PackageManagerSettings.asset
  ProjectSettings/Physics2DSettings.asset
  ProjectSettings/PresetManager.asset
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/ProjectVersion.txt
  ProjectSettings/QualitySettings.asset
  ProjectSettings/SceneTemplateSettings.json
  ProjectSettings/ShaderGraphSettings.asset
  ProjectSettings/TagManager.asset
  ProjectSettings/TimeManager.asset
  ProjectSettings/TimelineSettings.asset
  ProjectSettings/URPProjectSettings.asset
  ProjectSettings/UnityConnectSettings.asset
  ProjectSettings/VFXManager.asset
  ProjectSettings/VersionControlSettings.asset
  ProjectSettings/XRSettings.asset
  README.md
Labels: DEV | new feature

#24 [AP] Task-0: New project hot fix
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/DynamicsManager.asset
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/EditorSettings.asset
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/ProjectVersion.txt
  ProjectSettings/ShaderGraphSettings.asset
  ProjectSettings/TimelineSettings.asset
Labels: DEV | fix

#27 [AA] Update Gitignore
  .gitignore
Labels: DEV | refactoring
