Repository GamedevExperienceStables/gamedev-experience-stables, pull requests merged in 2023-02, with the labels that each got.

#48 Upgraded gameplay editor boot
  Assets/Game/Level/Prefabs/Core/EditorBoot.prefab
  Assets/Game/Level/Prefabs/Core/GameplayEditorBoot.prefab
  Assets/Game/Level/Prefabs/Core/GameplayEditorBoot.prefab.meta
  Assets/Game/Scripts/GameFlow/PlanetGameplay/PlanetLocationLoadingState.cs
  Assets/Game/Scripts/Level/Interactions/TransitionToLocationInteraction.cs
  Assets/Game/Scripts/Level/LevelController.cs
  Assets/Game/Scripts/Level/LevelData.cs
  Assets/Game/Scripts/Level/Location/ILocationDefinition.cs
  Assets/Game/Scripts/Level/Location/ILocationDefinition.cs.meta
  Assets/Game/Scripts/Level/Location/ILocationPoint.cs
  Assets/Game/Scripts/Level/Location/ILocationPoint.cs.meta
  Assets/Game/Scripts/Level/Location/ILocationPointKey.cs
  Assets/Game/Scripts/Level/Location/ILocationPointKey.cs.meta
  Assets/Game/Scripts/Level/Location/ILocationPointKeyOwner.cs
  Assets/Game/Scripts/Level/Location/ILocationPointKeyOwner.cs.meta
  Assets/Game/Scripts/Level/Location/Location.cs
  Assets/Game/Scripts/Level/Location/Location.cs.meta
  Assets/Game/Scripts/Level/Location/LocationDefinition.cs
  Assets/Game/Scripts/Level/Location/LocationPoint.Editor.cs
  Assets/Game/Scripts/Level/Location/LocationPoint.Editor.cs.meta
  Assets/Game/Scripts/Level/Location/LocationPoint.cs
  Assets/Game/Scripts/Level/Location/LocationPointData.cs
  Assets/Game/Scripts/Level/Location/LocationPointDefinition.cs
  Assets/Game/Scripts/Level/Location/LocationPointKey.cs
  Assets/Game/Scripts/Level/Location/LocationPointStaticDefinition.cs
  Assets/Game/Scripts/Level/LocationContext.cs
  Assets/Game/Scripts/Persistence/Handlers/LevelImportExport.cs
  Assets/Game/Scripts/Settings/LevelDefinition.cs
  Assets/Game/Scripts/Settings/LevelsSettings.cs
  Assets/Game/Scripts/Utils/GameplayEditorBoot.Editor.cs
  Assets/Game/Scripts/Utils/GameplayEditorBoot.Editor.cs.meta
  Assets/Game/Scripts/Utils/GameplayEditorBoot.cs
  Assets/Game/Test/TestLocation.unity
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/EditorSettings.asset
Labels: DEV | new feature

#44 [AP] Implemented save/load system
  Assets/Game/Level/Data/Settings/GameDataTables.asset
  Assets/Game/Level/Data/Settings/GameDataTables.asset.meta
  Assets/Game/Level/Data/Settings/GameSettings.asset
  Assets/Game/Level/Prefabs/Core/RootLifetimeScope.prefab
  Assets/Game/Level/Scenes/Levels/Rocket.unity
  Assets/Game/Scripts/GameFlow/Root/LoadGameState.cs
  Assets/Game/Scripts/GameFlow/Root/LoadGameState.cs.meta
  Assets/Game/Scripts/GameFlow/Root/RootStateMachine.cs
  Assets/Game/Scripts/Inventory/InventoryController.cs
  Assets/Game/Scripts/Inventory/InventoryInitialData.cs
  Assets/Game/Scripts/Inventory/InventoryInitialData.cs.meta
  Assets/Game/Scripts/Inventory/Items/Materials/MaterialContainer.cs
  Assets/Game/Scripts/Inventory/Items/Materials/MaterialInitialData.cs
  Assets/Game/Scripts/Inventory/Items/Materials/MaterialInitialData.cs.meta
  Assets/Game/Scripts/Inventory/Items/Materials/Materials.cs
  Assets/Game/Scripts/Inventory/Items/Recipes/IReadOnlyRecipes.cs
  Assets/Game/Scripts/Inventory/Items/Recipes/Recipes.cs
  Assets/Game/Scripts/Inventory/Items/Runes/IReadOnlyRunes.cs
  Assets/Game/Scripts/Inventory/Items/Runes/Runes.cs
  Assets/Game/Scripts/Level/Interactables/SavePoint.cs
  Assets/Game/Scripts/Level/Interactables/SavePoint.cs.meta
  Assets/Game/Scripts/Level/Interactions/InteractionBindingMap.cs
  Assets/Game/Scripts/Level/Interactions/SaveGameInteraction.cs
  Assets/Game/Scripts/Level/Interactions/SaveGameInteraction.cs.meta
  Assets/Game/Scripts/LifetimeScopes/GameplayLifetimeScope.cs
  Assets/Game/Scripts/LifetimeScopes/RootLifetimeScope.cs
  Assets/Game/Scripts/Persistence/GameSaveData.cs
  Assets/Game/Scripts/Persistence/Handlers/GameImportExport.cs
  Assets/Game/Scripts/Persistence/Handlers/LevelImportExport.cs
  Assets/Game/Scripts/Persistence/Handlers/PlayerImportExport.cs
  Assets/Game/Scripts/Persistence/LocalPersistence.cs
  Assets/Game/Scripts/Persistence/PersistenceService.cs
  Assets/Game/Scripts/Settings/GameDataTables.cs
  Assets/Game/Scripts/Settings/GameDataTables.cs.meta
  Assets/Game/Scripts/Settings/LevelsSettings.cs
  Assets/Game/Scripts/UI/Constants/LayoutNames.cs
  Assets/Game/Scripts/UI/MainMenu/StartMenuView.cs
  Assets/Game/Scripts/UI/MainMenu/StartMenuViewModel.cs
  Assets/Game/UI/Uxml/StartMenu.uxml
Labels: DEV | new feature

#49 [AA] Spawn system
  Assembly-CSharp.csproj.DotSettings
  Assets/Game/Level/Prefabs/Enemies/Spawner/EnemySpawnPoint.prefab
  Assets/Game/Level/Prefabs/Enemies/Spawner/EnemySpawnPoint.prefab.meta
  Assets/Game/Level/Prefabs/Enemies/Spawner/EnemySpawnZone.prefab
  Assets/Game/Level/Prefabs/Enemies/Spawner/EnemySpawnZone.prefab.meta
  Assets/Game/Level/Prefabs/Hero/Hero.prefab
  Assets/Game/Level/Scenes/Levels/Planet1_Dungeon1.unity
  Assets/Game/Scripts/Enemies/EnemySpawnPoint.cs
  Assets/Game/Scripts/Enemies/EnemySpawnPoint.cs.meta
  Assets/Game/Scripts/Enemies/EnemySpawnTrigger.cs
  Assets/Game/Scripts/Enemies/EnemySpawnTrigger.cs.meta
  Assets/Game/Scripts/Enemies/EnemySpawnZone.cs
  Assets/Game/Scripts/Enemies/EnemySpawnZone.cs.meta
  Assets/Game/Scripts/Hero/HeroController.cs
  Assets/Game/Scripts/Level/LocationContext.cs
  Assets/Game/Scripts/Level/Triggers.meta
  Assets/Game/Scripts/Level/Triggers/ISpawnZoneTrigger.cs
  Assets/Game/Scripts/Level/Triggers/ISpawnZoneTrigger.cs.meta
Labels: DEV | new feature

#52 [AP] Fixes and rethink
  Assets/BehaviourTree/Editor/BehaviourTreeEditorWindow.cs
  Assets/Game/Level/Data/PlanetLocations/PointKeys/Planet_Rocket.asset
  Assets/Game/Level/Data/PlanetLocations/PointKeys/Rocket.asset
  Assets/Game/Level/Data/PlanetLocations/PointKeys/Rocket.asset.meta
  Assets/Game/Level/Prefabs/Enemies/Spawner/EnemySpawnTrigger.prefab
  Assets/Game/Level/Prefabs/Enemies/Spawner/EnemySpawnTrigger.prefab.meta
  Assets/Game/Level/Prefabs/Enemies/Spawner/EnemySpawnZone.prefab
  Assets/Game/Level/Scenes/Levels/Planet1.unity
  Assets/Game/Level/Scenes/Levels/Planet1_Dungeon1.unity
  Assets/Game/Level/Scenes/Templates.meta
  Assets/Game/Level/Scenes/Templates/GameplayTemplateScene.meta
  Assets/Game/Level/Scenes/Templates/GameplayTemplateScene.scenetemplate
  Assets/Game/Level/Scenes/Templates/GameplayTemplateScene.scenetemplate.meta
  Assets/Game/Level/Scenes/Templates/GameplayTemplateScene.unity
  Assets/Game/Level/Scenes/Templates/GameplayTemplateScene.unity.meta
  Assets/Game/Level/Scenes/Templates/GameplayTemplateScene/LightingData.asset
  Assets/Game/Level/Scenes/Templates/GameplayTemplateScene/LightingData.asset.meta
  Assets/Game/Level/Scenes/Templates/GameplayTemplateScene/ReflectionProbe-0.exr
  Assets/Game/Level/Scenes/Templates/GameplayTemplateScene/ReflectionProbe-0.exr.meta
  Assets/Game/Scripts/Actors/Abilities/AutoPickupAbilityDefinition.cs
  Assets/Game/Scripts/Enemies/EnemyDefinition.cs
  Assets/Game/Scripts/Enemies/EnemySpawnTrigger.cs
  Assets/Game/Scripts/Enemies/EnemySpawnZone.cs
  Assets/Game/Scripts/GameFlow/PlanetGameplay/PlanetLocationLoadingState.cs
  Assets/Game/Scripts/Hero/HeroDefinition.cs
  Assets/Game/Scripts/Level/Interactables/LocationDoor.cs
  Assets/Game/Scripts/Level/Interactions/TransitionToLocationInteraction.cs
  Assets/Game/Scripts/Level/Location/LocationDefinition.cs
  Assets/Game/Scripts/Level/Location/LocationPoint.cs
  Assets/Game/Scripts/Level/Location/LocationPointDynamicDefinition.cs
  Assets/Game/Scripts/Level/Location/LocationPointKey.cs
  Assets/Game/Scripts/Level/Location/LocationPointStaticDefinition.cs
  Assets/Game/Scripts/Level/Location/LocationTypeDefinition.cs
  Assets/Game/Scripts/Level/Location/LocationTypeDefinition.cs.meta
  Assets/Game/Scripts/Level/LocationContext.cs
  Assets/Game/Scripts/Level/Loot/LootBagDefinition.cs
  Assets/Game/Scripts/Level/Loot/LootItemDefinition.cs
  Assets/Game/Scripts/Settings/LevelDefinition.cs
  Assets/Game/Scripts/Utils/DataTable/DataTableDefinition.cs
Labels: DEV | refactoring

#51 [AI] dash melee
  Assets/Game/Level/Data/Hero/HeroDashAbility.asset
  Assets/Game/Level/Data/Hero/HeroDashAbility.asset.meta
  Assets/Game/Level/Data/Hero/HeroData.asset
  Assets/Game/Level/Data/Hero/HeroMeleeAbility.asset
  Assets/Game/Level/Data/Hero/HeroMeleeAbility.asset.meta
  Assets/Game/Level/Data/Hero/HeroRecoveryAbility.asset
  Assets/Game/Level/Data/Hero/HeroRecoveryAbility.asset.meta
  Assets/Game/Level/Prefabs/Enemies/SpaceZombie.prefab
  Assets/Game/Level/Prefabs/Weapons/Bullets/BasicBullet.prefab
  Assets/Game/Level/Scenes/Templates/GameplayTemplateScene.scenetemplate
  Assets/Game/Scripts/Actors/Abilities/DashAbilityDefenition.cs
  Assets/Game/Scripts/Actors/Abilities/DashAbilityDefenition.cs.meta
  Assets/Game/Scripts/Actors/Abilities/MeleeAbilityDefinition.cs
  Assets/Game/Scripts/Actors/Abilities/MeleeAbilityDefinition.cs.meta
  Assets/Game/Scripts/Actors/Abilities/RecoveryAbilityDefinition.cs
  Assets/Game/Scripts/Actors/Abilities/RecoveryAbilityDefinition.cs.meta
  Assets/Game/Scripts/Hero/HeroInputController.cs
  Assets/Game/Scripts/Input/InputControlGameplay.cs
  Assets/Game/Scripts/LifetimeScopes/GameplayLifetimeScope.cs
  Assets/Game/Scripts/Utils/LayerMasks.cs
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/TagManager.asset
Labels: DEV | new feature

#54 [AP] add version and fix cancel ability
  Assets/Game/Scripts/Actors/Abilities/ActorAbility.cs
  Assets/Game/UI/Uxml/StartMenu.uxml
  ProjectSettings/ProjectSettings.asset
Labels: DEV | fix, DEV | refactoring

#55 [AP] Added local timers
  Assets/Game/Scripts/GameFlow/PlanetGameplay/PlanetPauseState.cs
  Assets/Game/Scripts/LifetimeScopes/RootLifetimeScope.cs
  Assets/Game/Scripts/TimeManagement/ITimeProvider.cs
  Assets/Game/Scripts/TimeManagement/ITimeProvider.cs.meta
  Assets/Game/Scripts/TimeManagement/ITimeService.cs
  Assets/Game/Scripts/TimeManagement/ITimeService.cs.meta
  Assets/Game/Scripts/TimeManagement/TimeService.cs
  Assets/Game/Scripts/TimeManagement/TimerFactory.cs
  Assets/Game/Scripts/TimeManagement/TimerFactory.cs.meta
  Assets/Game/Scripts/TimeManagement/TimerUpdatable.cs
  Assets/Game/Scripts/TimeManagement/TimerUpdatable.cs.meta
Labels: DEV | new feature

#58 AI/CameraAngle
  Assets/Game/Level/Scenes/Core/GameplayPlanet.unity
Labels: DEV | refactoring

#60 [AP] Implemented hero death
  Assets/Game/Level/Data/Hero/HeroData.asset
  Assets/Game/Level/Data/Hero/HeroReviveAbility.asset
  Assets/Game/Level/Data/Hero/HeroReviveAbility.asset.meta
  Assets/Game/Level/Data/Loot/Item_Scroll_Revive.asset
  Assets/Game/Level/Data/Loot/Item_Scroll_Revive.asset.meta
  Assets/Game/Level/Data/Runes/2Rank/Rune2_Passive1.asset
  Assets/Game/Level/Data/Runes/3Rank.meta
  Assets/Game/Level/Data/Runes/3Rank/Rune3_Revive.asset
  Assets/Game/Level/Data/Runes/3Rank/Rune3_Revive.asset.meta
  Assets/Game/Level/Prefabs/Items/Scrolls.meta
  Assets/Game/Level/Prefabs/Items/Scrolls/Item_Scroll.prefab
  Assets/Game/Level/Prefabs/Items/Scrolls/Item_Scroll.prefab.meta
  Assets/Game/Level/Prefabs/UI/GameOver.prefab
  Assets/Game/Level/Prefabs/UI/GameOver.prefab.meta
  Assets/Game/Level/Scenes/Core/GameplayPlanet.unity
  Assets/Game/Scripts/Actors/Abilities/ActorAbility.cs
  Assets/Game/Scripts/Actors/Abilities/ReviveAbilityDefinition.cs
  Assets/Game/Scripts/Actors/Abilities/ReviveAbilityDefinition.cs.meta
  Assets/Game/Scripts/Actors/ActorAbilities.cs
  Assets/Game/Scripts/Actors/ActorController.cs
  Assets/Game/Scripts/Actors/Health/DamageableController.cs
  Assets/Game/Scripts/Actors/Health/DeathController.cs
  Assets/Game/Scripts/Actors/IActorController.cs
  Assets/Game/Scripts/Actors/IActorInputController.cs
  Assets/Game/Scripts/Actors/IActorInputController.cs.meta
  Assets/Game/Scripts/Enemies/AiController.cs
  Assets/Game/Scripts/GameFlow/PlanetGameplay/GameplayBackButton.cs
  Assets/Game/Scripts/GameFlow/PlanetGameplay/GameplayBackButton.cs.meta
  Assets/Game/Scripts/GameFlow/PlanetGameplay/GameplayEntryPoint.cs
  Assets/Game/Scripts/GameFlow/PlanetGameplay/GameplayGameOver.cs
  Assets/Game/Scripts/GameFlow/PlanetGameplay/GameplayGameOver.cs.meta
  Assets/Game/Scripts/GameFlow/PlanetGameplay/GameplayInputTracker.cs
  Assets/Game/Scripts/GameFlow/PlanetGameplay/GameplayPause.cs
  Assets/Game/Scripts/GameFlow/PlanetGameplay/GameplayPause.cs.meta
  Assets/Game/Scripts/GameFlow/PlanetGameplay/PlanetGameOverState.cs
  Assets/Game/Scripts/GameFlow/PlanetGameplay/PlanetGameOverState.cs.meta
  Assets/Game/Scripts/GameFlow/PlanetGameplay/PlanetPauseState.cs
  Assets/Game/Scripts/GameFlow/PlanetGameplay/PlanetPlayState.cs
  Assets/Game/Scripts/GameFlow/PlanetGameplay/PlanetStateMachine.cs
  Assets/Game/Scripts/Hero/HeroFactory.cs
  Assets/Game/Scripts/Hero/HeroInputController.cs
  Assets/Game/Scripts/Input/InputSchema.cs
  Assets/Game/Scripts/Input/InputSchema.cs.meta
  Assets/Game/Scripts/Level/LevelGoalChecker.cs
  Assets/Game/Scripts/Level/ZoneDamageablePeriodic.cs
  Assets/Game/Scripts/Level/ZoneDamageablePeriodic.cs.meta
  Assets/Game/Scripts/Level/ZoneEffect.cs
  Assets/Game/Scripts/LifetimeScopes/GameplayLifetimeScope.cs
  Assets/Game/Scripts/Player/PlayerController.cs
  Assets/Game/Scripts/UI/Constants/LayoutNames.cs
  Assets/Game/Scripts/UI/Gameplay/GameOverView.cs
  Assets/Game/Scripts/UI/Gameplay/GameOverView.cs.meta
  Assets/Game/Scripts/UI/Gameplay/GameplayView.cs
  Assets/Game/Scripts/UI/Gameplay/GameplayViewModel.cs
  Assets/Game/Test/TestLocation.unity
  Assets/Game/UI/Uxml/GameOver.uxml
  Assets/Game/UI/Uxml/GameOver.uxml.meta
Labels: DEV | new feature

#59 [AA] Update hud
  Assets/Game/Level/Data/Crystals/Crystal_Blue.asset
  Assets/Game/Level/Data/Crystals/Crystal_Green.asset
  Assets/Game/Level/Data/Crystals/Crystal_Red.asset
  Assets/Game/Level/Data/Crystals/Crystal_Yellow.asset
  Assets/Game/Scripts/Inventory/Items/Materials/IReadOnlyMaterialContainer.cs
  Assets/Game/Scripts/Inventory/Items/Materials/IReadOnlyMaterialData.cs
  Assets/Game/Scripts/Inventory/Items/Materials/IReadOnlyMaterialData.cs.meta
  Assets/Game/Scripts/Inventory/Items/Materials/MaterialContainer.cs
  Assets/Game/Scripts/Inventory/Items/Materials/MaterialData.cs
  Assets/Game/Scripts/Inventory/Items/Materials/MaterialDefinition.cs
  Assets/Game/Scripts/Level/LevelController.cs
  Assets/Game/Scripts/UI/Constants/LayoutNames.cs
  Assets/Game/Scripts/UI/Gameplay/GameplayViewModel.cs
  Assets/Game/Scripts/UI/Gameplay/HudView.cs
  Assets/Game/UI/Textures.meta
  Assets/Game/UI/Textures/HUD_atlas.psd
  Assets/Game/UI/Textures/HUD_atlas.psd.meta
  Assets/Game/UI/Uss.meta
  Assets/Game/UI/Uss/HudStyle.uss
  Assets/Game/UI/Uss/HudStyle.uss.meta
  Assets/Game/UI/Uxml/Hud.uxml
  Assets/Game/UI/Uxml/Partial/PropertyWidget.uxml
  Assets/Game/UI/Uxml/Partial/Spell.uxml
  Assets/Game/UI/Uxml/Partial/Spell.uxml.meta
Labels: DEV | new feature

#63 [AP] Better FMOD gitignore
  .gitignore
Labels: DEV | refactoring

#68 [AP] Dash fix
  Assets/Game/Scripts/Actors/Abilities/DashAbilityDefenition.cs
  Assets/Game/Scripts/Actors/MovementController.cs
Labels: DEV | fix

#74 [AI] Snoody model
  Assets/Game/Art/Materials/Coat.mat
  Assets/Game/Art/Materials/Coat.mat.meta
  Assets/Game/Art/Materials/Hero.mat
  Assets/Game/Art/Materials/Hero.mat.meta
  Assets/Game/Art/Models/main_character_sprint1.fbx
  Assets/Game/Art/Models/main_character_sprint1.fbx.meta
  Assets/Game/Art/Textures/character_diffuse.png
  Assets/Game/Art/Textures/character_diffuse.png.meta
  Assets/Game/Art/Textures/coat_diffuse.png
  Assets/Game/Art/Textures/coat_diffuse.png.meta
  Assets/Game/Level/Prefabs/Hero/Hero.prefab
  ProjectSettings/URPProjectSettings.asset
Labels: ART | new feature

#75 [AP] Update fixes
  Assets/Game/Scripts/GameFlow/Root/LoadGameState.cs
  Assets/Game/UI/Uxml/StartMenu.uxml
  ProjectSettings/ProjectSettings.asset
Labels: DEV | fix

#77 [AA] Update HUD
  Assets/Game/Scripts/UI/Constants/LayoutNames.cs
  Assets/Game/Scripts/UI/Gameplay/HudView.cs
  Assets/Game/UI/Textures/HUD_atlas.psd
  Assets/Game/UI/Textures/HUD_atlas.psd.meta
  Assets/Game/UI/Uss/HudStyle.uss
  Assets/Game/UI/Uxml/Hud.uxml
Labels: DEV | refactoring

#83 [AP] Added initial runes
  Assets/Game/Level/Data/Settings/GameSettings.asset
  Assets/Game/Scripts/Actors/Abilities/MeleeAbilityDefinition.cs
  Assets/Game/Scripts/Inventory/InventoryData.cs
  Assets/Game/Scripts/Inventory/InventorySettings.cs
  Assets/Game/Scripts/Inventory/InventorySettings.cs.meta
  Assets/Game/Scripts/Persistence/Handlers/PlayerImportExport.cs
  Assets/Game/Scripts/Settings/GameSettings.cs
Labels: DEV | new feature

#86 [AP] Fix projectiles
  Assets/Game/Level/Data/Hero/RuneAbilities/Fire/HeroFireProjectile.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/Water/HeroWaterAbility.asset
  Assets/Game/Level/Prefabs/Hero/Runes/DefaultBullet.prefab
  Assets/Game/Level/Prefabs/Hero/Runes/FireBullet.prefab
  Assets/Game/Level/Prefabs/Hero/Runes/InfernoBullet.prefab
  Assets/Game/Level/Prefabs/Hero/Runes/WaterBullet.prefab
  Assets/Game/Level/Prefabs/Weapons/Bullets/BasicBulletZombie.prefab
  Assets/Game/Scripts/Weapons/Projectile.cs
Labels: DEV | fix

#85 [AA] Update behaviour tree
  Assets/Game/Level/Data/BehaviourTree/AngryEnemyAi.asset
  Assets/Game/Level/Prefabs/Enemies/SpaceZombie.prefab
  Assets/Game/Level/Prefabs/Hero/Hero.prefab
  Assets/Game/Scripts/BehaviourTree/Actions/Attack.cs
  Assets/Game/Scripts/BehaviourTree/Conditions/CheckHealth.cs
  Assets/Game/Scripts/BehaviourTree/Conditions/IsSeeHero.cs
  Assets/Game/Scripts/BehaviourTree/Conditions/IsSeeHero.cs.meta
  Assets/Game/Scripts/Enemies/AiController.cs
  Assets/Game/Scripts/Enemies/AiSensor.cs
  Assets/Game/Scripts/Enemies/AiSensor.cs.meta
  Assets/Game/Scripts/Enemies/AttackSettings.cs
  Assets/Game/Scripts/Enemies/AttackSettings.cs.meta
  Assets/Game/Scripts/Enemies/EnemyController.cs
  Assets/Game/Scripts/Enemies/EnemyFactory.cs
  Assets/Game/Scripts/Enemies/EnemyStats.cs
Labels: DEV | refactoring
