Repository GamedevExperienceStables/gamedev-experience-stables, pull requests merged in 2023-03, with the labels that each got.

#91 [AP] Changed dash movement
  Assets/Game/Scripts/Actors/Abilities/DashAbilityDefenition.cs
  Assets/Game/Scripts/Actors/IActorInputController.cs
  Assets/Game/Scripts/Actors/MovementController.cs
  Assets/Game/Scripts/Enemies/AiController.cs
  Assets/Game/Scripts/Hero/HeroInputController.cs
Labels: DEV | fix

#92 [AA] Update HUD
  Assets/Game/Scripts/Inventory/Items/Runes/RuneDefinition.cs
  Assets/Game/Scripts/UI/Constants/LayoutNames.cs
  Assets/Game/Scripts/UI/Gameplay/Elements/RuneSlotDraggerElement.cs
  Assets/Game/Scripts/UI/Gameplay/RuneSlots/RuneSlotHudView.cs
  Assets/Game/Scripts/UI/Gameplay/RuneSlots/RuneSlotInventoryView.cs
  Assets/Game/UI/Textures/Empty_runes.psd
  Assets/Game/UI/Textures/Empty_runes.psd.meta
  Assets/Game/UI/Textures/HUD_atlas.psd
  Assets/Game/UI/Textures/HUD_atlas.psd.meta
  Assets/Game/UI/Uss/HudStyle.uss
  Assets/Game/UI/Uxml/Hud.uxml
  Assets/Game/UI/Uxml/Partial/Spell.uxml
Labels: DEV | refactoring

#97 [AP] Implement passive runes
  Assets/Game/Level/Data/Animations/HeroAnimationController.controller
  Assets/Game/Level/Data/Enemies/M1/M1_Melee.asset
  Assets/Game/Level/Data/Enemies/M3/M3_Melee.asset
  Assets/Game/Level/Data/Hero/BaseAbilitites/HeroDashAbility.asset
  Assets/Game/Level/Data/Hero/BaseAbilitites/HeroMeleeAbility.asset
  Assets/Game/Level/Data/Hero/HeroData.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/HeroDashUpgrade.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/HeroDashUpgrade.asset.meta
  Assets/Game/Level/Data/Hero/RuneAbilities/HeroMeleeUpgrade.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/HeroMeleeUpgrade.asset.meta
  Assets/Game/Level/Data/Loot/Item_Scroll_DashUpgrade.asset
  Assets/Game/Level/Data/Loot/Item_Scroll_DashUpgrade.asset.meta
  Assets/Game/Level/Data/Loot/Item_Scroll_MeleeUpgrade.asset
  Assets/Game/Level/Data/Loot/Item_Scroll_MeleeUpgrade.asset.meta
  Assets/Game/Level/Data/Runes/2Rank/Rune2_PassiveDash.asset
  Assets/Game/Level/Data/Runes/2Rank/Rune2_PassiveMelee.asset
  Assets/Game/Scripts/Actors/Abilities/DashAbilityDefenition.cs
  Assets/Game/Scripts/Actors/Abilities/MeleeAbilityDefinition.cs
  Assets/Game/Scripts/Actors/Abilities/StatsModifiersAbilityDefinition.cs
  Assets/Game/Scripts/Actors/Abilities/StatsModifiersAbilityDefinition.cs.meta
  Assets/Game/Scripts/Actors/Damage/DamageDealer.cs
  Assets/Game/Scripts/Actors/Health/DamageableController.cs
  Assets/Game/Scripts/Actors/Health/DeathController.cs
  Assets/Game/Scripts/Animations/Hero/AnimationView.cs
  Assets/Game/Scripts/Hero/HeroStats.cs
  Assets/Game/Scripts/Level/ZoneDamageInstant.cs
  Assets/Game/Scripts/Level/ZoneDamageablePeriodic.cs
  Assets/Game/Scripts/LifetimeScopes/GameplayLifetimeScope.cs
  Assets/Game/Scripts/Stats/CharacterStatModifier.cs
  Assets/Game/Scripts/Stats/CharacterStatModifier.cs.meta
  Assets/Game/Scripts/Stats/CharacterStats.cs
  Assets/Game/Scripts/Weapons/ProjectileBehaviour.cs
  Assets/Game/Test/TestLocation/Targets/___TestLootBag.asset
Labels: DEV | new feature

#98 [AP] Interaction visualization
  Assembly-CSharp.csproj.DotSettings
  Assets/Game/Level/Data/PlanetLocations/PointKeys/Rocket_SavePoint.asset
  Assets/Game/Level/Data/PlanetLocations/PointKeys/Rocket_SavePoint.asset.meta
  Assets/Game/Level/Data/PlanetLocations/Points/Static/Rocket_SavePoint.asset
  Assets/Game/Level/Data/PlanetLocations/Points/Static/Rocket_SavePoint.asset.meta
  Assets/Game/Level/Data/Settings/GameSettings.asset
  Assets/Game/Level/Scenes/Levels/Rocket.unity
  Assets/Game/Scripts/GameFlow/PlanetGameplay/PlanetSaveGameState.cs
  Assets/Game/Scripts/GameFlow/PlanetGameplay/PlanetSaveGameState.cs.meta
  Assets/Game/Scripts/GameFlow/PlanetGameplay/PlanetStateMachine.cs
  Assets/Game/Scripts/GameFlow/Root/LoadGameState.cs
  Assets/Game/Scripts/Level/Interactions/InteractionService.cs
  Assets/Game/Scripts/Level/Interactions/SaveGameInteraction.cs
  Assets/Game/Scripts/LifetimeScopes/GameplayLifetimeScope.cs
  Assets/Game/Scripts/Persistence/Handlers/LevelImportExport.cs
  Assets/Game/Scripts/Persistence/PersistenceService.cs
  Assets/Game/Scripts/Settings/LevelsSettings.cs
  Assets/Game/Scripts/UI/Constants/LayoutNames.cs
  Assets/Game/Scripts/UI/Gameplay/HudView.cs
  Assets/Game/Scripts/UI/Gameplay/Interaction.meta
  Assets/Game/Scripts/UI/Gameplay/Interaction/InteractionView.cs
  Assets/Game/Scripts/UI/Gameplay/Interaction/InteractionView.cs.meta
  Assets/Game/Scripts/UI/Gameplay/Interaction/InteractionViewModel.cs
  Assets/Game/Scripts/UI/Gameplay/Interaction/InteractionViewModel.cs.meta
  Assets/Game/Scripts/UI/Gameplay/Interaction/SavingView.cs
  Assets/Game/Scripts/UI/Gameplay/Interaction/SavingView.cs.meta
  Assets/Game/Scripts/UI/Gameplay/Interaction/SavingViewModel.cs
  Assets/Game/Scripts/UI/Gameplay/Interaction/SavingViewModel.cs.meta
  Assets/Game/Scripts/Utils/VisualElementExtensions.cs
  Assets/Game/UI/Uss/HudStyle.uss
  Assets/Game/UI/Uxml/Hud.uxml
  Assets/Game/UI/Uxml/Partial/InteractionWidget.uxml
  Assets/Game/UI/Uxml/Partial/InteractionWidget.uxml.meta
  Assets/Game/UI/Uxml/Partial/SavingWidget.uxml
  Assets/Game/UI/Uxml/Partial/SavingWidget.uxml.meta
Labels: DEV | new feature

#88 [AA/AP] Add mini map
  Assembly-CSharp.csproj.DotSettings
  Assets/Game/Art/Locations.meta
  Assets/Game/Art/Locations/L1.meta
  Assets/Game/Art/Locations/L1/L1_Map.bak.png
  Assets/Game/Art/Locations/L1/L1_Map.bak.png.meta
  Assets/Game/Art/Locations/L1/L1_Map.png
  Assets/Game/Art/Locations/L1/L1_Map.png.meta
  Assets/Game/Level/Prefabs/Level/LevelBoundaries.prefab
  Assets/Game/Level/Prefabs/Level/LevelBoundaries.prefab.meta
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/L1.asset
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1_Small.unity
  Assets/Game/Scripts/GameFlow/PlanetGameplay/PlanetGameOverState.cs
  Assets/Game/Scripts/GameFlow/PlanetGameplay/PlanetLocationLoadingState.cs
  Assets/Game/Scripts/Level/ILocationBounds.cs
  Assets/Game/Scripts/Level/ILocationBounds.cs.meta
  Assets/Game/Scripts/Level/Location/ILocationDefinition.cs
  Assets/Game/Scripts/Level/Location/Location.cs
  Assets/Game/Scripts/Level/Location/LocationDefinition.cs
  Assets/Game/Scripts/Level/LocationBounds.cs
  Assets/Game/Scripts/Level/LocationBounds.cs.meta
  Assets/Game/Scripts/Level/LocationContext.cs
  Assets/Game/Scripts/Level/LocationController.cs
  Assets/Game/Scripts/LifetimeScopes/GameplayLifetimeScope.cs
  Assets/Game/Scripts/UI/Gameplay/HudRuneSlots/HudRuneSlotsView.cs
  Assets/Game/Scripts/UI/Gameplay/HudView.cs
  Assets/Game/Scripts/UI/Gameplay/MiniMap.meta
  Assets/Game/Scripts/UI/Gameplay/MiniMap/MiniMapView.cs
  Assets/Game/Scripts/UI/Gameplay/MiniMap/MiniMapView.cs.meta
  Assets/Game/Scripts/UI/Gameplay/MiniMap/MiniMapViewModel.cs
  Assets/Game/Scripts/UI/Gameplay/MiniMap/MiniMapViewModel.cs.meta
  Assets/Game/Scripts/Utils/GameplayEditorBoot.Editor.cs
  Assets/Game/Scripts/Utils/MathExtensions.cs
  Assets/Game/UI/Uss/HudStyle.uss
  Assets/Game/UI/Uss/MapStyle.uss
  Assets/Game/UI/Uss/MapStyle.uss.meta
  Assets/Game/UI/Uxml/Hud.uxml
  Assets/Game/UI/Uxml/Partial/MiniMap.uxml
  Assets/Game/UI/Uxml/Partial/MiniMap.uxml.meta
Labels: DEV | new feature

#101 [AA] Update Book
  Assets/Game/Level/Data/Runes/1Rank/Rune1_Earth.asset
  Assets/Game/Level/Data/Runes/1Rank/Rune1_Fire.asset
  Assets/Game/Level/Data/Runes/1Rank/Rune1_Water.asset
  Assets/Game/Level/Data/Runes/1Rank/Rune1_Wind.asset
  Assets/Game/Level/Data/Runes/2Rank/Rune2_Lava.asset
  Assets/Game/Level/Data/Runes/2Rank/Rune2_Life.asset
  Assets/Game/Level/Data/Runes/2Rank/Rune2_Lighting.asset
  Assets/Game/Level/Data/Runes/2Rank/Rune2_PassiveDash.asset
  Assets/Game/Level/Data/Runes/2Rank/Rune2_PassiveMelee.asset
  Assets/Game/Level/Data/Runes/2Rank/Rune2_Wave.asset
  Assets/Game/Level/Data/Runes/3Rank/Rune3_Revive.asset
  Assets/Game/Level/Data/Runes/DataTable_Runes.asset
  Assets/Game/Level/Data/Runes/Levels.meta
  Assets/Game/Level/Data/Runes/Levels/Rune_L1.asset
  Assets/Game/Level/Data/Runes/Levels/Rune_L1.asset.meta
  Assets/Game/Level/Data/Runes/Levels/Rune_L2.asset
  Assets/Game/Level/Data/Runes/Levels/Rune_L2.asset.meta
  Assets/Game/Level/Data/Runes/Levels/Rune_L3.asset
  Assets/Game/Level/Data/Runes/Levels/Rune_L3.asset.meta
  Assets/Game/Level/Data/Runes/Levels/Rune_Passive.asset
  Assets/Game/Level/Data/Runes/Levels/Rune_Passive.asset.meta
  Assets/Game/Scripts/Inventory/Items/Runes/RuneDefinition.cs
  Assets/Game/Scripts/Inventory/Items/Runes/RuneLevelDefinition.cs
  Assets/Game/Scripts/Inventory/Items/Runes/RuneLevelDefinition.cs.meta
  Assets/Game/Scripts/UI/Constants/LayoutNames.cs
  Assets/Game/Scripts/UI/Gameplay/Inventory/InventoryView.cs
  Assets/Game/Scripts/UI/Gameplay/RuneSlots/RuneSlotHoverEvent.cs
  Assets/Game/Scripts/UI/Gameplay/RuneSlots/RuneSlotHoverEvent.cs.meta
  Assets/Game/Scripts/UI/Gameplay/RuneSlots/RuneSlotInventoryView.cs
  Assets/Game/UI/Textures/Magic_Book_Atlas.psd
  Assets/Game/UI/Textures/Magic_Book_Atlas.psd.meta
  Assets/Game/UI/Textures/Rune_Atlas.psd
  Assets/Game/UI/Textures/Rune_Atlas.psd.meta
  Assets/Game/UI/Uss/HudStyle.uss
  Assets/Game/UI/Uss/MagicBookStyle.uss
  Assets/Game/UI/Uxml/Hud.uxml
  Assets/Game/UI/Uxml/MagicBook.uxml
  Assets/Game/UI/Uxml/Partial/Spell.uxml
  debug.log
Labels: DEV | refactoring

#104 [AP] New Game fix
  Assets/Game/Scripts/Inventory/Items/Materials/Materials.cs
  Assets/Game/Scripts/Inventory/Slots/RuneSlots.cs
Labels: DEV | fix

#103 [AP] Implemented markers on mini map
  Assets/Game/Level/Data/LocationMarkers.meta
  Assets/Game/Level/Data/LocationMarkers/DungeonMarker.asset
  Assets/Game/Level/Data/LocationMarkers/DungeonMarker.asset.meta
  Assets/Game/Level/Data/LocationMarkers/RocketMarker.asset
  Assets/Game/Level/Data/LocationMarkers/RocketMarker.asset.meta
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1_Small.unity
  Assets/Game/Scripts/LifetimeScopes/GameplayLifetimeScope.cs
  Assets/Game/Scripts/UI/Constants/LayoutNames.cs
  Assets/Game/Scripts/UI/Gameplay/MiniMap/ILocationMarker.cs
  Assets/Game/Scripts/UI/Gameplay/MiniMap/ILocationMarker.cs.meta
  Assets/Game/Scripts/UI/Gameplay/MiniMap/LocationMarker.cs
  Assets/Game/Scripts/UI/Gameplay/MiniMap/LocationMarker.cs.meta
  Assets/Game/Scripts/UI/Gameplay/MiniMap/LocationMarkers.cs
  Assets/Game/Scripts/UI/Gameplay/MiniMap/LocationMarkers.cs.meta
  Assets/Game/Scripts/UI/Gameplay/MiniMap/MapMarker.cs
  Assets/Game/Scripts/UI/Gameplay/MiniMap/MapMarker.cs.meta
  Assets/Game/Scripts/UI/Gameplay/MiniMap/MapMarkerDefinition.cs
  Assets/Game/Scripts/UI/Gameplay/MiniMap/MapMarkerDefinition.cs.meta
  Assets/Game/Scripts/UI/Gameplay/MiniMap/MiniMap.cs
  Assets/Game/Scripts/UI/Gameplay/MiniMap/MiniMap.cs.meta
  Assets/Game/Scripts/UI/Gameplay/MiniMap/MiniMapMarkers.cs
  Assets/Game/Scripts/UI/Gameplay/MiniMap/MiniMapMarkers.cs.meta
  Assets/Game/Scripts/UI/Gameplay/MiniMap/MiniMapView.cs
  Assets/Game/Scripts/UI/Gameplay/MiniMap/MiniMapViewModel.cs
  Assets/Game/Scripts/Utils/MathExtensions.cs
  Assets/Game/UI/Uss/MapStyle.uss
  Assets/NotForProduction/MapIcons.meta
  Assets/NotForProduction/MapIcons/Icons_04.png
  Assets/NotForProduction/MapIcons/Icons_04.png.meta
  Assets/NotForProduction/MapIcons/Icons_12.png
  Assets/NotForProduction/MapIcons/Icons_12.png.meta
  Assets/NotForProduction/MapIcons/Icons_21.png
  Assets/NotForProduction/MapIcons/Icons_21.png.meta
  Assets/NotForProduction/MapIcons/Icons_23.png
  Assets/NotForProduction/MapIcons/Icons_23.png.meta
  Assets/NotForProduction/MapIcons/Icons_24.png
  Assets/NotForProduction/MapIcons/Icons_24.png.meta
Labels: DEV | new feature

#109 [IP] Improved balance
  Assets/Game/Level/Data/Consumables/Stone_Health.asset
  Assets/Game/Level/Data/Enemies/M1/M1_Melee.asset
  Assets/Game/Level/Data/Enemies/M1_SmallMelee.asset
  Assets/Game/Level/Data/Enemies/M2/M2_Projectile.asset
  Assets/Game/Level/Data/Enemies/M2/M2_ProjectileDamage.asset
  Assets/Game/Level/Data/Enemies/M2_SmallRange.asset
  Assets/Game/Level/Data/Hero/BaseAbilitites/HeroAimAbility.asset
  Assets/Game/Level/Data/Hero/BaseAbilitites/HeroDashAbility.asset
  Assets/Game/Level/Data/Hero/BaseAbilitites/HeroMeleeAbility.asset
  Assets/Game/Level/Data/Hero/BaseAbilitites/HeroPickupAbility.asset
  Assets/Game/Level/Data/Hero/BaseAbilitites/HeroRecoveryAbility.asset
  Assets/Game/Level/Data/Hero/HeroData.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/Default/HeroDefaultProjectileDamage.asset
  Assets/Game/Level/Data/PlanetLocations/PointKeys/Rocket.asset
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1_Small.unity
Labels: GD | refactoring
