Repository GamedevExperienceStables/gamedev-experience-stables, pull requests merged in 2023-04, with the labels that each got.

#116 [DB] Idle Anmation
  Assets/Game/Art/Monsters/M2/Animations/M2_Idle.fbx
  Assets/Game/Art/Monsters/M2/Animations/M2_Idle.fbx.meta
  Assets/Game/Art/Monsters/M3/Animations/M3_Idle.fbx
  Assets/Game/Art/Monsters/M3/Animations/M3_Idle.fbx.meta
  Assets/Game/Art/Monsters/M4/Animations/M4 Idle.fbx
  Assets/Game/Art/Monsters/M4/Animations/M4 Idle.fbx.meta
  Assets/Game/Level/Data/Animations/Generic/M2.overrideController
  Assets/Game/Level/Data/Animations/Generic/M3.overrideController
  Assets/Game/Level/Data/Animations/Generic/M4.overrideController
Labels: ART | refactoring

#113 [AA] Update menu
  Assembly-CSharp.csproj.DotSettings
  Assets/Game/Level/Data/Localization/ImportedSheets/Localization - GUI.csv
  Assets/Game/Level/Data/Localization/ImportedSheets/Localization - GamePlay.csv
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI_be.asset
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI_en.asset
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI_ru.asset
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI_uk.asset
  Assets/Game/Level/Data/Localization/Tables/GamePlay/GamePlay Shared Data.asset
  Assets/Game/Level/Data/Localization/Tables/GamePlay/GamePlay_be.asset
  Assets/Game/Level/Data/Localization/Tables/GamePlay/GamePlay_en.asset
  Assets/Game/Level/Data/Localization/Tables/GamePlay/GamePlay_ru.asset
  Assets/Game/Level/Data/Localization/Tables/GamePlay/GamePlay_uk.asset
  Assets/Game/Level/Data/Settings/GameSettings.asset
  Assets/Game/Level/Data/Settings/UISettings.asset
  Assets/Game/Level/Data/Settings/UISettings.asset.meta
  Assets/Game/Level/Scenes/Core/MainMenu.unity
  Assets/Game/Scripts/LifetimeScopes/RootLifetimeScope.cs
  Assets/Game/Scripts/Localization/ILocalizationService.cs
  Assets/Game/Scripts/Localization/LocalizationTable.cs
  Assets/Game/Scripts/Localization/LocalizationTable.cs.meta
  Assets/Game/Scripts/Localization/UnityLocalization.cs
  Assets/Game/Scripts/Settings/FaderSettings.cs
  Assets/Game/Scripts/Settings/FaderSettings.cs.meta
  Assets/Game/Scripts/Settings/GameSettings.cs
  Assets/Game/Scripts/Settings/UiSettings.cs
  Assets/Game/Scripts/Settings/UiSettings.cs.meta
  Assets/Game/Scripts/UI/Common/PageRouter.cs
  Assets/Game/Scripts/UI/Constants/LayoutNames.cs
  Assets/Game/Scripts/UI/MainMenu/AboutView.cs
  Assets/Game/Scripts/UI/MainMenu/AboutViewModel.cs
  Assets/Game/Scripts/UI/MainMenu/ArtView.cs
  Assets/Game/Scripts/UI/MainMenu/ArtViewModel.cs
  Assets/Game/Scripts/UI/MainMenu/MainMenuSettingsView.cs
  Assets/Game/Scripts/UI/MainMenu/MainMenuViewRouter.cs
  Assets/Game/Scripts/UI/MainMenu/PreviewView.cs
  Assets/Game/Scripts/UI/MainMenu/PreviewView.cs.meta
  Assets/Game/Scripts/UI/MainMenu/StartMenuView.cs
  Assets/Game/Scripts/UI/Settings/SettingsView.cs
  Assets/Game/UI/Fonts/borsok SDF.asset
  Assets/Game/UI/Fonts/koliko-Bold SDF.asset
  Assets/Game/UI/Fonts/koliko-Regular SDF.asset
  Assets/Game/UI/Textures/Menu_Atlas_new.psd
  Assets/Game/UI/Textures/Menu_Atlas_new.psd.meta
  Assets/Game/UI/Textures/Menu_Background_Atlas.psd
  Assets/Game/UI/Textures/Menu_Background_Atlas.psd.meta
  Assets/Game/UI/Textures/Menu_Book_Atlas.psd
  Assets/Game/UI/Textures/Menu_Book_Atlas.psd.meta
  Assets/Game/UI/Uss/MainMenuStyle.uss
  Assets/Game/UI/Uss/SettingsScreenStyle.uss
  Assets/Game/UI/Uss/SettingsScreenStyle.uss.meta
  Assets/Game/UI/Uxml/Partial/FooterBar.uxml
  Assets/Game/UI/Uxml/Partial/FooterBar.uxml.meta
  Assets/Game/UI/Uxml/Partial/MenuButton.uxml
  Assets/Game/UI/Uxml/Partial/SettingsControls.uxml
  Assets/Game/UI/Uxml/StartScreen/Preview.uxml
  Assets/Game/UI/Uxml/StartScreen/Preview.uxml.meta
  Assets/Game/UI/Uxml/StartScreen/SettingsScreen.uxml
  Assets/Game/UI/Uxml/StartScreen/StartMenu.uxml
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  ProjectSettings/ProjectSettings.asset
Labels: DEV | refactoring

#117 [IP] Updated monsters balance
  Assets/Game/Level/Data/Enemies/M1/M1_Melee.asset
  Assets/Game/Level/Data/Enemies/M1_SmallMelee.asset
  Assets/Game/Level/Data/Enemies/M_LE_m.asset
  Assets/Game/Level/Data/Enemies/M_LE_m.asset.meta
  Assets/Game/Level/Data/Enemies/M_LE_m.meta
  Assets/Game/Level/Data/Enemies/M_LE_m/M_LE_m_meele.asset
  Assets/Game/Level/Data/Enemies/M_LE_m/M_LE_m_meele.asset.meta
  Assets/Game/Level/Data/Enemies/M_LE_r.asset
  Assets/Game/Level/Data/Enemies/M_LE_r.asset.meta
  Assets/Game/Level/Data/Enemies/M_LE_r.meta
  Assets/Game/Level/Data/Enemies/M_LE_r/M_LE_r_Projectile.asset
  Assets/Game/Level/Data/Enemies/M_LE_r/M_LE_r_Projectile.asset.meta
  Assets/Game/Level/Data/Enemies/M_LE_r/M_LE_r_ProjectileDamage.asset
  Assets/Game/Level/Data/Enemies/M_LE_r/M_LE_r_ProjectileDamage.asset.meta
  Assets/Game/Level/Data/Enemies/M_LE_r/M_LE_r_Range.asset
  Assets/Game/Level/Data/Enemies/M_LE_r/M_LE_r_Range.asset.meta
  Assets/Game/Level/Data/Enemies/M_LN_m.asset
  Assets/Game/Level/Data/Enemies/M_LN_m.asset.meta
  Assets/Game/Level/Data/Enemies/M_LN_m.meta
  Assets/Game/Level/Data/Enemies/M_LN_m/M_LN_m_meele.asset
  Assets/Game/Level/Data/Enemies/M_LN_m/M_LN_m_meele.asset.meta
  Assets/Game/Level/Data/Enemies/M_LN_r.asset
  Assets/Game/Level/Data/Enemies/M_LN_r.asset.meta
  Assets/Game/Level/Data/Enemies/M_LN_r.meta
  Assets/Game/Level/Data/Enemies/M_LN_r/M_LN_r_Projectile.asset
  Assets/Game/Level/Data/Enemies/M_LN_r/M_LN_r_Projectile.asset.meta
  Assets/Game/Level/Data/Enemies/M_LN_r/M_LN_r_ProjectileDamage.asset
  Assets/Game/Level/Data/Enemies/M_LN_r/M_LN_r_ProjectileDamage.asset.meta
  Assets/Game/Level/Data/Enemies/M_LN_r/M_LN_r_Range.asset
  Assets/Game/Level/Data/Enemies/M_LN_r/M_LN_r_Range.asset.meta
  Assets/Game/Level/Data/Enemies/M_SE_m.asset
  Assets/Game/Level/Data/Enemies/M_SE_m.asset.meta
  Assets/Game/Level/Data/Enemies/M_SE_m.meta
  Assets/Game/Level/Data/Enemies/M_SE_m/M_SE_m_meele.asset
  Assets/Game/Level/Data/Enemies/M_SE_m/M_SE_m_meele.asset.meta
  Assets/Game/Level/Data/Enemies/M_SE_r.asset
  Assets/Game/Level/Data/Enemies/M_SE_r.asset.meta
  Assets/Game/Level/Data/Enemies/M_SE_r.meta
  Assets/Game/Level/Data/Enemies/M_SE_r/M_SE_r_Projectile.asset
  Assets/Game/Level/Data/Enemies/M_SE_r/M_SE_r_Projectile.asset.meta
  Assets/Game/Level/Data/Enemies/M_SE_r/M_SE_r_ProjectileDamage.asset
  Assets/Game/Level/Data/Enemies/M_SE_r/M_SE_r_ProjectileDamage.asset.meta
  Assets/Game/Level/Data/Enemies/M_SE_r/M_SE_r_Range.asset
  Assets/Game/Level/Data/Enemies/M_SE_r/M_SE_r_Range.asset.meta
  Assets/Game/Level/Data/Enemies/M_SN_m.asset
  Assets/Game/Level/Data/Enemies/M_SN_m.asset.meta
  Assets/Game/Level/Data/Enemies/M_SN_m.meta
  Assets/Game/Level/Data/Enemies/M_SN_m/M_SN_m_meele.asset
  Assets/Game/Level/Data/Enemies/M_SN_m/M_SN_m_meele.asset.meta
  Assets/Game/Level/Data/Enemies/M_SN_r.asset
  Assets/Game/Level/Data/Enemies/M_SN_r.asset.meta
  Assets/Game/Level/Data/Enemies/M_SN_r.meta
  Assets/Game/Level/Data/Enemies/M_SN_r/M_SN_r_Projectile.asset
  Assets/Game/Level/Data/Enemies/M_SN_r/M_SN_r_Projectile.asset.meta
  Assets/Game/Level/Data/Enemies/M_SN_r/M_SN_r_ProjectileDamage.asset
  Assets/Game/Level/Data/Enemies/M_SN_r/M_SN_r_ProjectileDamage.asset.meta
  Assets/Game/Level/Data/Enemies/M_SN_r/M_SN_r_Range.asset
  Assets/Game/Level/Data/Enemies/M_SN_r/M_SN_r_Range.asset.meta
  Assets/Game/Level/Data/Hero/BaseAbilitites/HeroAimAbility.asset
  nottrojanfile.jpg
Labels: GD | refactoring

#120 Snoody Balance Update
  Assets/Game/Level/Data/Consumables/Stone_Health.asset
  Assets/Game/Level/Data/Consumables/Stone_Mana.asset
  Assets/Game/Level/Data/Consumables/Stone_Stamina.asset
  Assets/Game/Level/Data/Enemies/M1/M1_Melee.asset
  Assets/Game/Level/Data/Enemies/M1_SmallMelee.asset
  Assets/Game/Level/Data/Enemies/M2/M2_Projectile.asset
  Assets/Game/Level/Data/Enemies/M2/M2_ProjectileDamage.asset
  Assets/Game/Level/Data/Enemies/M2/M2_Range.asset
  Assets/Game/Level/Data/Enemies/M3/M3_Melee.asset
  Assets/Game/Level/Data/Enemies/M3_LargeMelee.asset
  Assets/Game/Level/Data/Enemies/M4/M4_Projectile.asset
  Assets/Game/Level/Data/Enemies/M4/M4_ProjectileDamage.asset
  Assets/Game/Level/Data/Enemies/M4_LargeRange.asset
  Assets/Game/Level/Data/Enemies/M_SE_m.asset
  Assets/Game/Level/Data/Enemies/M_SE_m/M_SE_m_meele.asset
  Assets/Game/Level/Data/Enemies/M_SE_r.asset
  Assets/Game/Level/Data/Enemies/M_SE_r/M_SE_r_Projectile.asset
  Assets/Game/Level/Data/Enemies/M_SE_r/M_SE_r_ProjectileDamage.asset
  Assets/Game/Level/Data/Enemies/M_SE_r/M_SE_r_Range.asset
  Assets/Game/Level/Data/Hero/BaseAbilitites/HeroAimAbility.asset
  Assets/Game/Level/Data/Hero/BaseAbilitites/HeroDashAbility.asset
  Assets/Game/Level/Data/Hero/BaseAbilitites/HeroMeleeAbility.asset
  Assets/Game/Level/Data/Hero/BaseAbilitites/HeroRecoveryAbility.asset
  Assets/Game/Level/Data/Hero/HeroData.asset
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1V2.unity
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1V3.unity
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
Labels: GD | refactoring

#122 [AP] Implemented cloak cloth
  Assets/Game/Art/Hero/Animations/Idle_v001.fbx.meta
  Assets/Game/Art/Hero/Materials/HeroCoat.mat
  Assets/Game/Level/Prefabs/Hero/Hero.prefab
  Packages/manifest.json
  Packages/packages-lock.json
Labels: DEV | new feature, ART | new feature

#121 [AP] Quick fix update
  Assets/Game/Art/Common/Shaders/Fog.shadersubgraph
  Assets/Game/Art/Common/Shaders/Fog.shadersubgraph.meta
  Assets/Game/Art/Common/Shaders/ObstructedDither.shadergraph
  Assets/Game/Art/Common/Shaders/ObstructedDither.shadergraph.meta
  Assets/Game/Art/Hero/Materials/HeroObstructedDither.mat
  Assets/Game/Art/Hero/Materials/HeroObstructedDither.mat.meta
  Assets/Game/Level/Data/Enemies/M_SE_r/M_SE_r_ProjectileDamage.asset
  Assets/Game/Level/Data/Enemies/M_SN_r/M_SN_r_ProjectileDamage.asset
  Assets/Game/Level/Prefabs/Hero/Hero.prefab
  Assets/Game/Level/Prefabs/UI/Common/Version.prefab
  Assets/Game/Level/Prefabs/UI/Common/Version.prefab.meta
  Assets/Game/Level/Prefabs/UI/Gameplay/GameplayUI.prefab
  Assets/Game/Level/Scenes/Core/GameplayPlanet.unity
  Assets/Game/Level/Scenes/Core/MainMenu.unity
  Assets/Game/Scripts/LifetimeScopes/MainMenuLifetimeScope.cs
  Assets/Game/Scripts/UI/Common/VersionView.cs
  Assets/Game/Scripts/UI/Common/VersionView.cs.meta
  Assets/Game/Scripts/UI/Constants/LayoutNames.cs
  Assets/Game/Scripts/UI/Gameplay/MiniMap/MiniMapView.cs
  Assets/Game/Settings/URP/URP-Balanced-Renderer.asset
  Assets/Game/Settings/URP/URP-HighFidelity-Renderer.asset
  Assets/Game/Settings/URP/URP-Performant-Renderer.asset
  Assets/Game/UI/Fonts/borsok SDF.asset
  Assets/Game/UI/Fonts/koliko-Regular SDF.asset
  Assets/Game/UI/Uss/MapStyle.uss
  Assets/Game/UI/Uxml/Partial/FooterBar.uxml
  Assets/Game/UI/Uxml/Partial/MiniMap.uxml
  Assets/Game/UI/Uxml/StartScreen/StartMenu.uxml
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  ProjectSettings/ProjectSettings.asset
Labels: DEV | fix, DEV | refactoring

#128 [AP] UI modals
  Assembly-CSharp.csproj.DotSettings
  Assets/Game/Level/Data/Localization/ImportedSheets/Localization - GUI.csv
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI Shared Data.asset
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI_be.asset
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI_en.asset
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI_ru.asset
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI_uk.asset
  Assets/Game/Level/Data/Settings/UISettings.asset
  Assets/Game/Level/Prefabs/UI/Common/Modal.prefab
  Assets/Game/Level/Prefabs/UI/Common/Modal.prefab.meta
  Assets/Game/Level/Prefabs/UI/Gameplay/GameplayUI.prefab
  Assets/Game/Level/Scenes/Core/MainMenu.unity
  Assets/Game/Scripts/LifetimeScopes/GameplayLifetimeScope.cs
  Assets/Game/Scripts/LifetimeScopes/MainMenuLifetimeScope.cs
  Assets/Game/Scripts/LifetimeScopes/RootLifetimeScope.cs
  Assets/Game/Scripts/UI/Constants/LayoutNames.cs
  Assets/Game/Scripts/UI/Gameplay/PauseMenuView.cs
  Assets/Game/Scripts/UI/Gameplay/PauseMenuViewModel.cs
  Assets/Game/Scripts/UI/MainMenu/MainMenuViewRouter.cs
  Assets/Game/Scripts/UI/MainMenu/StartMenuView.cs
  Assets/Game/Scripts/UI/MainMenu/StartMenuViewModel.cs
  Assets/Game/Scripts/UI/Modal.meta
  Assets/Game/Scripts/UI/Modal/ModalContext.cs
  Assets/Game/Scripts/UI/Modal/ModalContext.cs.meta
  Assets/Game/Scripts/UI/Modal/ModalService.cs
  Assets/Game/Scripts/UI/Modal/ModalService.cs.meta
  Assets/Game/Scripts/UI/Modal/ModalSettings.cs
  Assets/Game/Scripts/UI/Modal/ModalSettings.cs.meta
  Assets/Game/Scripts/UI/Modal/ModalView.cs
  Assets/Game/Scripts/UI/Modal/ModalView.cs.meta
  Assets/Game/Scripts/UI/Modal/ModalViewModel.cs
  Assets/Game/Scripts/UI/Modal/ModalViewModel.cs.meta
  Assets/Game/UI/Uxml/Common.meta
  Assets/Game/UI/Uxml/Common/Modal.uxml
  Assets/Game/UI/Uxml/Common/Modal.uxml.meta
  Assets/Game/UI/Uxml/PauseScreen.uxml
  Assets/Game/UI/Uxml/StartScreen/MenuBookScreen.uxml
  Assets/Game/UI/Uxml/StartScreen/MenuBookScreen.uxml.meta
  Assets/Game/UI/Uxml/StartScreen/StartMenu.uxml
Labels: DEV | refactoring, DEV | new feature

#131 [KD] Fix bugs
  Assets/Game/Art/Environment/Aqueduct/aqueduct.prefab
  Assets/Game/Art/Environment/flowers/flower01.prefab
  Assets/Game/Art/Environment/flowers/flower02.prefab
  Assets/Game/Art/Environment/flowers/flower04.prefab
  Assets/Game/Art/Environment/trees/Tree01.prefab
  Assets/Game/Art/Environment/trees/Tree02.prefab
  Assets/Game/Art/Environment/trees/Tree03.prefab
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1 1.asset
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1V3.unity
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1V3/NavMesh-NavMeshSurfaces.asset
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1V3/OcclusionCullingData.asset
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1V3/OcclusionCullingData.asset.meta
  Assets/Game/Level/Scenes/Levels/GameLevel/L1D1/Level_1_Dung_1/OcclusionCullingData.asset
  Assets/Game/Level/Scenes/Levels/GameLevel/L1D2/Level_1_Dung_2/OcclusionCullingData.asset
  Assets/LowPoly Rocks/FBX/arch.prefab
Labels: GD | new feature

#130 [AP] Added attack animation speed multiplier
  Assets/Game/Level/Data/Animations/Generic/GenericEnemy.controller
  Assets/Game/Level/Data/Animations/HeroAnimationController.controller
  Assets/Game/Scripts/Actors/Abilities/MeleeAbilityDefinition.cs
  Assets/Game/Scripts/Actors/Abilities/ProjectileAbilityDefinition.cs
  Assets/Game/Scripts/Animations/Hero/AnimationNames.cs
Labels: DEV | new feature

#135 [IP] Enemy (M1 + M2) and Hero Balance
  Assets/Game/Level/Data/Enemies/EnemyProjectileTargeting.asset
  Assets/Game/Level/Data/Enemies/M_SE_m.asset
  Assets/Game/Level/Data/Enemies/M_SE_m/M_SE_m_meele.asset
  Assets/Game/Level/Data/Enemies/M_SE_r.asset
  Assets/Game/Level/Data/Enemies/M_SE_r/M_SE_r_Projectile.asset
  Assets/Game/Level/Data/Enemies/M_SE_r/M_SE_r_ProjectileDamage.asset
  Assets/Game/Level/Data/Enemies/M_SE_r/M_SE_r_Range.asset
  Assets/Game/Level/Data/Enemies/M_SN_m.asset
  Assets/Game/Level/Data/Enemies/M_SN_m/M_SN_m_meele.asset
  Assets/Game/Level/Data/Enemies/M_SN_r.asset
  Assets/Game/Level/Data/Hero/BaseAbilitites/HeroAimAbility.asset
  Assets/Game/Level/Data/Hero/HeroData.asset
  Assets/TestLocationIlia.unity
  Assets/TestLocationIlia.unity.meta
Labels: GD | refactoring

#132 [AA] Update UI
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI Shared Data.asset
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI_be.asset
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI_en.asset
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI_ru.asset
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI_uk.asset
  Assets/Game/Level/Data/Settings/UISettings.asset
  Assets/Game/Scripts/LifetimeScopes/RootLifetimeScope.cs
  Assets/Game/Scripts/Settings/UiSettings.cs
  Assets/Game/Scripts/UI/Constants/LayoutNames.cs
  Assets/Game/Scripts/UI/MainMenu/AboutView.cs
  Assets/Game/Scripts/UI/MainMenu/ArtView.cs
  Assets/Game/Scripts/UI/MainMenu/MainMenuSettingsView.cs
  Assets/Game/Scripts/UI/MainMenu/StartMenuView.cs
  Assets/Game/Scripts/UI/Settings/SettingsView.cs
  Assets/Game/UI/Fonts/borsok SDF.asset
  Assets/Game/UI/Fonts/koliko-Bold SDF.asset
  Assets/Game/UI/Fonts/koliko-Regular SDF.asset
  Assets/Game/UI/Textures/Menu_Atlas.psd.meta
  Assets/Game/UI/Uss/MainMenuStyle.uss
  Assets/Game/UI/Uss/ModalScreenStyle.uss
  Assets/Game/UI/Uss/ModalScreenStyle.uss.meta
  Assets/Game/UI/Uss/SettingsScreenStyle.uss
  Assets/Game/UI/Uxml/Common/Modal.uxml
  Assets/Game/UI/Uxml/Partial/SettingsControls.uxml
  Assets/Game/UI/Uxml/PauseSettings.uxml
  Assets/Game/UI/Uxml/PauseSettings.uxml.meta
  Assets/Game/UI/Uxml/StartScreen/SettingsScreen.uxml
  Assets/Game/UI/Uxml/StartScreen/StartMenu.uxml
Labels: DEV | refactoring, DEV | new feature

#133 [AS] Draft Balance
  Assets/Game/Level/Data/Enemies/M3_LargeMelee.asset
  Assets/Game/Level/Data/Enemies/M4/M4_ProjectileDamage.asset
  Assets/Game/Level/Data/Enemies/M4_LargeRange.asset
Labels: GD | new feature, GD | refactoring

#136 Kd/fix bugs dung
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1V3.unity
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1V3/NavMesh-NavMeshSurfaces 1.asset
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1V3/NavMesh-NavMeshSurfaces 1.asset.meta
  Assets/Game/Level/Scenes/Levels/GameLevel/L1D2/Level_1_Dung_2.unity
Labels: GD | refactoring

#139 [AP] Updated abilities UX
  Assets/Game/Level/Data/Localization/ImportedSheets/Localization - GUI.csv
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI Shared Data.asset
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI_be.asset
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI_en.asset
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI_ru.asset
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI_uk.asset
  Assets/Game/Scripts/Actors/Abilities/ActiveSkillAbilityDefinition.cs
  Assets/Game/Scripts/Actors/Abilities/AimAbilityDefinition.cs
  Assets/Game/Scripts/Actors/Abilities/DashAbilityDefinition.cs
  Assets/Game/Scripts/Actors/Abilities/InteractionAbilityDefinition.cs
  Assets/Game/Scripts/Actors/Abilities/MeleeAbilityDefinition.cs
  Assets/Game/Scripts/Actors/Abilities/ProjectileAbilityDefinition.cs
  Assets/Game/Scripts/Actors/ActorBlock.cs
  Assets/Game/Scripts/Actors/ActorInputController.cs
  Assets/Game/Scripts/Actors/ActorInputController.cs.meta
  Assets/Game/Scripts/Actors/Block/InputBlock.cs
  Assets/Game/Scripts/Actors/IActorInputController.cs
  Assets/Game/Scripts/Enemies/AiController.cs
  Assets/Game/Scripts/Hero/HeroController.cs
  Assets/Game/Scripts/Hero/HeroInputController.cs
  Assets/Game/Scripts/Input/GameInputControlsAdapter.cs
  Assets/Game/Scripts/Input/InputBindings.cs
  Assets/Game/Scripts/Input/InputGameplayActions.cs
  Assets/Game/Scripts/Player/PlayerController.cs
  Assets/Game/Scripts/UI/Constants/LayoutNames.cs
  Assets/Game/Scripts/UI/Gameplay/Elements/RuneDragAndDropManipulator.cs
  Assets/Game/Scripts/UI/Gameplay/HudRuneSlots/HudRuneSlotsView.cs
  Assets/Game/Scripts/UI/Gameplay/HudRuneSlots/HudRuneSlotsViewModel.cs
  Assets/Game/Scripts/UI/Gameplay/HudView.cs
  Assets/Game/Scripts/UI/Gameplay/Inventory/InventoryView.cs
  Assets/Game/Scripts/UI/Gameplay/RuneSlots/RuneSlotHudView.cs
  Assets/Game/Settings/UI Toolkit/PanelSettings.asset
  Assets/Game/Settings/UI Toolkit/UITK Text Settings.asset
  Assets/Game/Settings/UI Toolkit/UITK Text Settings.asset.meta
  Assets/Game/UI/Fonts/borsok SDF.asset
  Assets/Game/UI/Fonts/koliko-Bold SDF.asset
  Assets/Game/UI/Textures/Input.meta
  Assets/Game/UI/Textures/Input/input_tilemap_white_packed.asset
  Assets/Game/UI/Textures/Input/input_tilemap_white_packed.asset.meta
  Assets/Game/UI/Textures/Input/input_tilemap_white_packed.png
  Assets/Game/UI/Textures/Input/input_tilemap_white_packed.png.meta
  Assets/Game/UI/Uss/HudStyle.uss
  Assets/Game/UI/Uxml/Hud.uxml
  Assets/Game/UI/Uxml/Partial/HudRuneSlots.uxml
  Assets/Game/UI/Uxml/Partial/HudRuneSlots.uxml.meta
  Assets/Game/UI/Uxml/Partial/InventoryButtonWidget.uxml
  Assets/Game/UI/Uxml/Partial/InventoryButtonWidget.uxml.meta
  Assets/Game/UI/Uxml/Partial/Spell.uxml
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  ProjectSettings/ProjectSettings.asset
Labels: DEV | refactoring, DEV | new feature

#141 [AS] Runes Improved Balance
  Assets/Game/Level/Data/Hero/RuneAbilities/Default/HeroDefaultProjectile.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/Default/HeroDefaultProjectileDamage.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/Earth/HeroEarthProjectile.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/Earth/HeroEarthProjectileEffectStun.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/Fire/HeroFireProjectile.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/Fire/HeroFireProjectileEffectBurn.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/HeroEarthAbility.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/HeroFireAbility.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/HeroLavaAbility.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/HeroLifeAbility.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/HeroLightningAbility.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/HeroWaterAbility.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/HeroWaveAbility.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/HeroWindAbility.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/Lava/HeroLavaProjectile.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/Lava/HeroLavaPuddle.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/Lava/HeroLavaPuddleEffectBurn.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/Life/HeroLifeTree.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/Life/HeroLifeTreeRegenEffect.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/Lightning/HeroLightningProjectile.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/Lightning/HeroLightningProjectileDamageAoe.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/Water/HeroWaterProjectileDamageAoe.asset
Labels: GD | refactoring

#147 [NL] Corrected skull001 and skull002 at the level
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1V3.unity
Labels: GD | refactoring, ART | refactoring

#148 [AP] Magic book update
  Assets/Game/Scripts/GameFlow/PlanetGameplay/GameplayInventory.cs
  Assets/Game/Scripts/GameFlow/PlanetGameplay/GameplayMenuInput.cs
  Assets/Game/Scripts/Input/GameInputControls.cs
  Assets/Game/Scripts/Input/IInputControlGameplay.cs
  Assets/Game/Scripts/Input/InputControlGameplay.cs
  Assets/Game/Scripts/Inventory/IInventorySlots.cs
  Assets/Game/Scripts/Inventory/InventoryController.cs
  Assets/Game/Scripts/Inventory/Slots/RuneActiveSlot.cs
  Assets/Game/Scripts/Inventory/Slots/RuneSlots.cs
  Assets/Game/Scripts/UI/Constants/LayoutNames.cs
  Assets/Game/Scripts/UI/Gameplay/Elements/RuneDragAndDropManipulator.cs
  Assets/Game/Scripts/UI/Gameplay/Elements/RuneSlotDraggerElement.cs
  Assets/Game/Scripts/UI/Gameplay/HudRuneSlots/HudRuneSlotsView.cs
  Assets/Game/Scripts/UI/Gameplay/Inventory/InventoryView.cs
  Assets/Game/Scripts/UI/Gameplay/Inventory/InventoryViewModel.cs
  Assets/Game/Scripts/UI/Gameplay/RuneSlots/RuneSlotDragCompleteEvent.cs
  Assets/Game/Scripts/UI/Gameplay/RuneSlots/RuneSlotDragCompleteEvent.cs.meta
  Assets/Game/Scripts/UI/Gameplay/RuneSlots/RuneSlotDragEvent.cs
  Assets/Game/Scripts/UI/Gameplay/RuneSlots/RuneSlotHudView.cs
  Assets/Game/Scripts/UI/Gameplay/RuneSlots/RuneSlotInventoryView.cs
  Assets/Game/Settings/Input/GameInputControls.inputactions
  Assets/Game/UI/Uss/HudStyle.uss
  Assets/Game/UI/Uss/MagicBookStyle.uss
  Assets/Game/UI/Uxml/MagicBook.uxml
  Assets/Game/UI/Uxml/Partial/Spell.uxml
Labels: DEV | refactoring, DEV | new feature

#149 [AP] Fixed HUD rune swapping
  Assets/Game/Scripts/Inventory/IInventorySlots.cs
  Assets/Game/Scripts/Inventory/InventoryController.cs
  Assets/Game/Scripts/UI/Gameplay/Inventory/InventoryView.cs
  Assets/Game/Scripts/UI/Gameplay/Inventory/InventoryViewModel.cs
Labels: DEV | fix

#144 [AP] AI Nav update
  Assets/Game/Level/Data/BehaviourTree/AngryEnemyAi.asset
  Assets/Game/Level/Prefabs/Enemies/M2.prefab
  Assets/Game/Level/Prefabs/Enemies/M3.prefab
  Assets/Game/Level/Prefabs/Enemies/M4.prefab
  Assets/Game/Level/Prefabs/Enemies/MonsterBase.prefab
  Assets/Game/Level/Prefabs/Hero/Hero.prefab
  Assets/Game/Scripts/Actors/Health/DeathController.cs
  Assets/Game/Scripts/Actors/MovementController.cs
  Assets/Game/Scripts/BehaviourTree/Actions/MoveToActorController.cs
  Assets/Game/Scripts/Enemies/NavigationController.cs
  Assets/Game/Scripts/Utils/MathExtensions.cs
  Assets/Game/Test/TestLocation/Targets/TestTarget.prefab
  Assets/Game/Test/TestLocation/TestLocation.unity
  Assets/Game/Test/TestLocation/TestLocation/NavMesh-navmesh.asset
Labels: DEV | refactoring

#145 [AP] Update minimap
  Assets/Game/Art/Locations/L1/Level_1V3_1600.png
  Assets/Game/Art/Locations/L1/Level_1V3_1600.png.meta
  Assets/Game/Art/Locations/L1D1/Level_1_Dung_1_1600.png
  Assets/Game/Art/Locations/L1D1/Level_1_Dung_1_1600.png.meta
  Assets/Game/Art/Locations/L1D2/Level_1_Dung_2_1600.png
  Assets/Game/Art/Locations/L1D2/Level_1_Dung_2_1600.png.meta
  Assets/Game/Level/Data/LocationMarkers/DungeonMarker.asset
  Assets/Game/Level/Data/LocationMarkers/RocketMarker.asset
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/L1.asset
  Assets/Game/Level/Scenes/Levels/GameLevel/L1D1/L1D1.asset
  Assets/Game/Level/Scenes/Levels/GameLevel/L1D2/L1D2.asset
  Assets/Game/Scripts/UI/Gameplay/MiniMap/MapMarker.cs
  Assets/Game/Scripts/UI/Gameplay/MiniMap/MiniMapMarkers.cs
  Assets/Game/Scripts/UI/Gameplay/MiniMap/MiniMapView.cs
  Assets/Game/UI/Textures/Map.meta
  Assets/Game/UI/Textures/Map/Map_Snoody.png
  Assets/Game/UI/Textures/Map/Map_Snoody.png.meta
  Assets/Game/UI/Textures/Map/icon_door.png
  Assets/Game/UI/Textures/Map/icon_door.png.meta
  Assets/Game/UI/Textures/Map/icon_rocket.png
  Assets/Game/UI/Textures/Map/icon_rocket.png.meta
  Assets/Game/UI/Uss/MapStyle.uss
Labels: DEV | refactoring, ART | refactoring

#150 [AP] UI input update
  Assets/Game/Level/Data/Localization/ImportedSheets/Localization - GUI.csv
  Assets/Game/Level/Data/Localization/ImportedSheets/Localization - GamePlay.csv
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI Shared Data.asset
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI_be.asset
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI_en.asset
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI_ru.asset
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI_uk.asset
  Assets/Game/Level/Data/Localization/Tables/GamePlay/GamePlay_be.asset
  Assets/Game/Level/Data/Localization/Tables/GamePlay/GamePlay_en.asset
  Assets/Game/Level/Data/Localization/Tables/GamePlay/GamePlay_ru.asset
  Assets/Game/Level/Data/Localization/Tables/GamePlay/GamePlay_uk.asset
  Assets/Game/Level/Data/Settings/GameSettings.asset
  Assets/Game/Level/Data/Settings/UISettings.asset
  Assets/Game/Scripts/Input/InputBindings.cs
  Assets/Game/Scripts/Input/InputBindingsSettings.cs
  Assets/Game/Scripts/Input/InputBindingsSettings.cs.meta
  Assets/Game/Scripts/Input/InputKeyBinding.cs
  Assets/Game/Scripts/Input/InputKeyBinding.cs.meta
  Assets/Game/Scripts/Level/Interactions/InteractionPrompt.cs
  Assets/Game/Scripts/Level/Interactions/InteractionPrompt.cs.meta
  Assets/Game/Scripts/Level/Interactions/LocalizationInteraction.cs
  Assets/Game/Scripts/LifetimeScopes/GameplayLifetimeScope.cs
  Assets/Game/Scripts/LifetimeScopes/RootLifetimeScope.cs
  Assets/Game/Scripts/Settings/GameSettings.cs
  Assets/Game/Scripts/Settings/UiSettings.cs
  Assets/Game/Scripts/UI/Common/LoadingScreenView.cs
  Assets/Game/Scripts/UI/Constants/LayoutNames.cs
  Assets/Game/Scripts/UI/Cutscene/CutsceneActionSkip.cs
  Assets/Game/Scripts/UI/Elements/InputKey.cs
  Assets/Game/Scripts/UI/Elements/InputKey.cs.meta
  Assets/Game/Scripts/UI/Gameplay/HudPromptView.cs
  Assets/Game/Scripts/UI/Gameplay/HudPromptView.cs.meta
  Assets/Game/Scripts/UI/Gameplay/HudRuneSlots/HudRuneSlotsView.cs
  Assets/Game/Scripts/UI/Gameplay/HudSettings.cs
  Assets/Game/Scripts/UI/Gameplay/HudSettings.cs.meta
  Assets/Game/Scripts/UI/Gameplay/HudView.cs
  Assets/Game/Scripts/UI/Gameplay/Interaction/InteractionView.cs
  Assets/Game/Scripts/UI/Gameplay/Interaction/SavingView.cs
  Assets/Game/Scripts/UI/Gameplay/MiniMap/MiniMapView.cs
  Assets/Game/Scripts/UI/Gameplay/RuneSlots/RuneSlotHudView.cs
  Assets/Game/UI/Fonts/koliko-Bold SDF.asset
  Assets/Game/UI/Uss/Common.uss
  Assets/Game/UI/Uss/CutsceneStyle.uss
  Assets/Game/UI/Uss/HudStyle.uss
  Assets/Game/UI/Uss/MapStyle.uss
  Assets/Game/UI/Uxml/Cutscene/CutsceneScreen.uxml
  Assets/Game/UI/Uxml/Hud.uxml
  Assets/Game/UI/Uxml/LoadingScreen.uxml
  Assets/Game/UI/Uxml/Partial/InputKey.uxml
  Assets/Game/UI/Uxml/Partial/InputKey.uxml.meta
  Assets/Game/UI/Uxml/Partial/InteractionWidget.uxml
  Assets/Game/UI/Uxml/Partial/MagicBookPrompt.uxml
  Assets/Game/UI/Uxml/Partial/MagicBookPrompt.uxml.meta
  Assets/Game/UI/Uxml/Partial/MiniMap.uxml
  Assets/Game/UI/Uxml/Partial/SavingWidget.uxml
  Assets/Game/UI/Uxml/Partial/Spell.uxml
Labels: DEV | refactoring, DEV | new feature

#151 [AP] Fixed abnormal AI behavior
  Assets/Game/Level/Prefabs/Enemies/MonsterBase.prefab
  Assets/Game/Level/Prefabs/Hero/Hero.prefab
  Assets/Game/Scripts/Enemies/NavigationController.cs
Labels: DEV | fix

#153 [NL] Danzh1 spawns
  Assets/Game/Art/Monsters/M1/Materials/M1 Boss_Danzh1.mat
  Assets/Game/Art/Monsters/M1/Materials/M1 Boss_Danzh1.mat.meta
  Assets/Game/Art/Monsters/M1/Materials/M1.mat
  Assets/Game/Level/Data/Enemies/M_D1_Bo_m 1.asset
  Assets/Game/Level/Data/Enemies/M_D1_Bo_m 1.asset.meta
  Assets/Game/Level/Data/Enemies/M_D1_Bo_m 1.meta
  Assets/Game/Level/Data/Enemies/M_D1_Bo_m 1/M_D1_Bo_m 1.asset
  Assets/Game/Level/Data/Enemies/M_D1_Bo_m 1/M_D1_Bo_m 1.asset.meta
  Assets/Game/Level/Data/Loot/Bag/LootBag_Rune Bessmertia.asset
  Assets/Game/Level/Data/Loot/Bag/LootBag_Rune Bessmertia.asset.meta
  Assets/Game/Level/Prefabs/Enemies/M1 Boss_Danzh1.prefab
  Assets/Game/Level/Prefabs/Enemies/M1 Boss_Danzh1.prefab.meta
  Assets/Game/Level/Prefabs/Enemies/Spawner/EnemySpawnZone.prefab
  Assets/Game/Level/Prefabs/Enemies/Spawner/Parts/EnemySpawnPoint.prefab
  Assets/Game/Level/Scenes/Levels/GameLevel/L1D1/Level_1_Dung_1.unity
Labels: GD | refactoring, ART | refactoring

#155 [IP] Zones 3-4
  Assets/Game/Level/Data/Enemies/M_LE_m.asset
  Assets/Game/Level/Data/Enemies/M_LE_m/M_LE_m_meele.asset
  Assets/Game/Level/Data/Enemies/M_LE_m_WindRune+Crystall.asset
  Assets/Game/Level/Data/Enemies/M_LE_m_WindRune+Crystall.asset.meta
  Assets/Game/Level/Data/Enemies/M_LE_r.asset
  Assets/Game/Level/Data/Enemies/M_LE_r/M_LE_r_Projectile.asset
  Assets/Game/Level/Data/Enemies/M_LE_r/M_LE_r_ProjectileDamage.asset
  Assets/Game/Level/Data/Enemies/M_LE_r/M_LE_r_Range.asset
  Assets/Game/Level/Data/Enemies/M_LE_r_DashRune.asset
  Assets/Game/Level/Data/Enemies/M_LE_r_DashRune.asset.meta
  Assets/Game/Level/Data/Enemies/M_LE_r_FireRune+Crystall.asset
  Assets/Game/Level/Data/Enemies/M_LE_r_FireRune+Crystall.asset.meta
  Assets/Game/Level/Data/Enemies/M_LN_m.asset
  Assets/Game/Level/Data/Enemies/M_LN_m/M_LN_m_meele.asset
  Assets/Game/Level/Data/Enemies/M_LN_m_Crystall.asset
  Assets/Game/Level/Data/Enemies/M_LN_m_Crystall.asset.meta
  Assets/Game/Level/Data/Enemies/M_SE_m.asset
  Assets/Game/Level/Data/Enemies/M_SE_r.asset
  Assets/Game/Level/Data/Enemies/M_SE_r_Tut_1.asset
  Assets/Game/Level/Data/Enemies/M_SN_m.asset
  Assets/Game/Level/Data/Enemies/M_SN_m/M_SN_m_meele.asset
  Assets/Game/Level/Data/Enemies/M_SN_r.asset
  Assets/Game/Level/Data/Enemies/M_SN_r/M_SN_r_Projectile.asset
  Assets/Game/Level/Data/Enemies/M_SN_r/M_SN_r_ProjectileDamage.asset
  Assets/Game/Level/Data/Enemies/M_SN_r/M_SN_r_Range.asset
  Assets/Game/Level/Data/Loot/Bag/LootBag_M_LE_m.asset
  Assets/Game/Level/Data/Loot/Bag/LootBag_M_LE_m.asset.meta
  Assets/Game/Level/Data/Loot/Bag/LootBag_M_LE_m_WindRune.asset
  Assets/Game/Level/Data/Loot/Bag/LootBag_M_LE_m_WindRune.asset.meta
  Assets/Game/Level/Data/Loot/Bag/LootBag_M_LE_r.asset
  Assets/Game/Level/Data/Loot/Bag/LootBag_M_LE_r.asset.meta
  Assets/Game/Level/Data/Loot/Bag/LootBag_M_LE_r_DashRune.asset
  Assets/Game/Level/Data/Loot/Bag/LootBag_M_LE_r_DashRune.asset.meta
  Assets/Game/Level/Data/Loot/Bag/LootBag_M_LE_r_FireRune.asset
  Assets/Game/Level/Data/Loot/Bag/LootBag_M_LE_r_FireRune.asset.meta
  Assets/Game/Level/Data/Loot/Bag/LootBag_M_LN_m_GreenCrystall.asset
  Assets/Game/Level/Data/Loot/Bag/LootBag_M_LN_m_GreenCrystall.asset.meta
  Assets/Game/Level/Data/Loot/Bag/LootBag_M_SE_m.asset
  Assets/Game/Level/Data/Loot/Bag/LootBag_M_SE_m.asset.meta
  Assets/Game/Level/Data/Loot/Bag/LootBag_M_SE_r.asset
  Assets/Game/Level/Data/Loot/Bag/LootBag_M_SE_r.asset.meta
  Assets/Game/Level/Data/Loot/Item_Scroll_Wind.asset
  Assets/Game/Level/Data/Loot/Item_Scroll_Wind.asset.meta
  Assets/Game/Level/Data/Loot/Table/LootTable_M_LE_m.asset
  Assets/Game/Level/Data/Loot/Table/LootTable_M_LE_m.asset.meta
  Assets/Game/Level/Data/Loot/Table/LootTable_M_LE_r.asset
  Assets/Game/Level/Data/Loot/Table/LootTable_M_LE_r.asset.meta
  Assets/Game/Level/Data/Loot/Table/LootTable_M_SE_m.asset
  Assets/Game/Level/Data/Loot/Table/LootTable_M_SE_m.asset.meta
  Assets/Game/Level/Data/Loot/Table/LootTable_M_SE_r.asset
  Assets/Game/Level/Data/Loot/Table/LootTable_M_SE_r.asset.meta
  Assets/Game/Level/Prefabs/Level/Level_1/Zone_Ilya/Zone_Ilya.prefab
Labels: GD | new feature

#156 [NL] Danzh2_Spawns and Mobes
  Assets/Game/Art/Monsters/M3/Materials/M3 Boss_D2.mat
  Assets/Game/Art/Monsters/M3/Materials/M3 Boss_D2.mat.meta
  Assets/Game/Art/Monsters/M4/Materials/M4 Boss_D2.mat
  Assets/Game/Art/Monsters/M4/Materials/M4 Boss_D2.mat.meta
  Assets/Game/Level/Data/Enemies/M_D1_Bo_m 1.asset
  Assets/Game/Level/Data/Enemies/M_D1_Bo_m 1/M_D1_Bo_m 1.asset
  Assets/Game/Level/Data/Enemies/M_D2_Bos1.asset
  Assets/Game/Level/Data/Enemies/M_D2_Bos1.asset.meta
  Assets/Game/Level/Data/Enemies/M_D2_Bos1.meta
  Assets/Game/Level/Data/Enemies/M_D2_Bos1/M_D2_Bos1.asset
  Assets/Game/Level/Data/Enemies/M_D2_Bos1/M_D2_Bos1.asset.meta
  Assets/Game/Level/Data/Enemies/M_D2_Bos2.asset
  Assets/Game/Level/Data/Enemies/M_D2_Bos2.asset.meta
  Assets/Game/Level/Data/Enemies/M_D2_Bos2.meta
  Assets/Game/Level/Data/Enemies/M_D2_Bos2/M_D2_Bos2_Projectile.asset
  Assets/Game/Level/Data/Enemies/M_D2_Bos2/M_D2_Bos2_Projectile.asset.meta
  Assets/Game/Level/Data/Enemies/M_D2_Bos2/M_D2_Bos2_ProjectileDamage.asset
  Assets/Game/Level/Data/Enemies/M_D2_Bos2/M_D2_Bos2_ProjectileDamage.asset.meta
  Assets/Game/Level/Data/Enemies/M_D2_Bos2/M_D2_Bos2_Range.asset
  Assets/Game/Level/Data/Enemies/M_D2_Bos2/M_D2_Bos2_Range.asset.meta
  Assets/Game/Level/Data/Enemies/M_D2_Bos2/Monster_FireProjectileEffectBurn.asset
  Assets/Game/Level/Data/Enemies/M_D2_Bos2/Monster_FireProjectileEffectBurn.asset.meta
  Assets/Game/Level/Data/Enemies/M_D2_Bos3.asset
  Assets/Game/Level/Data/Enemies/M_D2_Bos3.asset.meta
  Assets/Game/Level/Data/Enemies/M_LE_m.asset
  Assets/Game/Level/Data/Enemies/M_LE_m/M_LE_m_meele.asset
  Assets/Game/Level/Data/Enemies/M_LN_m.asset
  Assets/Game/Level/Data/Enemies/M_LN_m/M_LN_m_meele.asset
  Assets/Game/Level/Data/Loot/Bag/LootBag_Lava.asset
  Assets/Game/Level/Data/Loot/Bag/LootBag_Lava.asset.meta
  Assets/Game/Level/Prefabs/Enemies/M1 Boss_Danzh1.prefab
  Assets/Game/Level/Prefabs/Enemies/M3 Boss_D2.prefab
  Assets/Game/Level/Prefabs/Enemies/M3 Boss_D2.prefab.meta
  Assets/Game/Level/Prefabs/Enemies/M4 Boss_D2.prefab
  Assets/Game/Level/Prefabs/Enemies/M4 Boss_D2.prefab.meta
  Assets/Game/Level/Prefabs/Weapons/Bullets/M_FireBullet.prefab
  Assets/Game/Level/Prefabs/Weapons/Bullets/M_FireBullet.prefab.meta
  Assets/Game/Level/Scenes/Levels/GameLevel/L1D1/Level_1_Dung_1.unity
  Assets/Game/Level/Scenes/Levels/GameLevel/L1D2/Level_1_Dung_2.unity
Labels: GD | refactoring

#157 [AS] Balance zone 5, 6, 7
  Assets/Game/Level/Data/Enemies/M_LE_m_GreenSrytal.asset
  Assets/Game/Level/Data/Enemies/M_LE_m_GreenSrytal.asset.meta
  Assets/Game/Level/Data/Enemies/M_LE_m_LightingScroll.asset
  Assets/Game/Level/Data/Enemies/M_LE_m_LightingScroll.asset.meta
  Assets/Game/Level/Data/Enemies/M_LE_r.asset
  Assets/Game/Level/Data/Enemies/M_LE_r_GreenCrystal.asset
  Assets/Game/Level/Data/Enemies/M_LE_r_GreenCrystal.asset.meta
  Assets/Game/Level/Data/Enemies/M_LN_m_WaveRune.asset
  Assets/Game/Level/Data/Enemies/M_LN_m_WaveRune.asset.meta
  Assets/Game/Level/Data/Enemies/M_SN_r_Green_Crystal_Loot.asset
  Assets/Game/Level/Data/Enemies/M_SN_r_Green_Crystal_Loot.asset.meta
  Assets/Game/Level/Data/Loot/Bag/LootBag_Lighting.asset
  Assets/Game/Level/Data/Loot/Bag/LootBag_Lighting.asset.meta
  Assets/Game/Level/Data/Loot/Bag/LootBag_RuneLighting.asset
  Assets/Game/Level/Data/Loot/Bag/LootBag_RuneLighting.asset.meta
  Assets/Game/Level/Data/Loot/Bag/LootBag_SE_m.asset
  Assets/Game/Level/Data/Loot/Item_Scroll_Lighting.asset
  Assets/Game/Level/Data/Loot/Item_Scroll_Lighting.asset.meta
  Assets/Game/Level/Data/Loot/Item_Scroll_Wave.asset
  Assets/Game/Level/Data/Loot/Item_Scroll_Wave.asset.meta
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1V3.unity
  Assets/TextMesh Pro/Documentation/TextMesh Pro User Guide 2016.pdf
  Assets/TextMesh Pro/Fonts/LiberationSans.ttf
  Assets/TextMesh Pro/Resources/Sprite Assets/EmojiOne.asset
  Assets/TextMesh Pro/Resources/Style Sheets/Default Style Sheet.asset
  Assets/TextMesh Pro/Resources/TMP Settings.asset
  Assets/TextMesh Pro/Sprites/EmojiOne.png
Labels: GD | new feature
