Repository GamedevExperienceStables/gamedev-experience-stables, pull requests merged in 2023-05, with the labels that each got.

#163 [AA] Refactor UI
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI Shared Data.asset
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI_be.asset
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI_en.asset
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI_ru.asset
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI_uk.asset
  Assets/Game/Level/Data/Settings/TeamsSettings.asset
  Assets/Game/Level/Data/Settings/UISettings.asset
  Assets/Game/Scripts/UI/Constants/LayoutNames.cs
  Assets/Game/Scripts/UI/MainMenu/About/AboutSettings.cs
  Assets/Game/Scripts/UI/MainMenu/About/AboutView.cs
  Assets/Game/Scripts/UI/MainMenu/About/EmployeeView.cs
  Assets/Game/Scripts/UI/MainMenu/About/EmployeeViewFactory.cs
  Assets/Game/Scripts/UI/MainMenu/About/TeamView.cs
  Assets/Game/Scripts/UI/MainMenu/About/TeamViewFactory.cs
  Assets/Game/Scripts/UI/MainMenu/About/TeamsView.cs
  Assets/Game/Scripts/UI/MainMenu/StartMenuView.cs
  Assets/Game/Scripts/UI/MainMenu/StartMenuViewModel.cs
  Assets/Game/UI/Fonts/borsok SDF.asset
  Assets/Game/UI/Uss/AboutScreenStyle.uss
  Assets/Game/UI/Uss/ScrollSliderStyle.uss
  Assets/Game/UI/Uxml/StartScreen/AboutScreen.uxml
  Assets/Game/UI/Uxml/StartScreen/ArtScreen.uxml
Labels: DEV | refactoring, DEV | new feature

#166 [KD] Level fix rock
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1 1.asset
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1V3.unity
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1V3/NavMesh-NavMeshSurfaces 1.asset
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1V3/NavMesh-NavMeshSurfaces 1.asset.meta
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1V3/NavMesh-NavMeshSurfaces.asset
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1V3/OcclusionCullingData.asset
Labels: GD | refactoring

#167 [AP] Updated save points
  Assets/Game/Art/Environment/Bonfire.meta
  Assets/Game/Art/Environment/Bonfire/Fireplace.mat
  Assets/Game/Art/Environment/Bonfire/Fireplace.mat.meta
  Assets/Game/Art/Environment/Bonfire/fireplace.fbx
  Assets/Game/Art/Environment/Bonfire/fireplace.fbx.meta
  Assets/Game/Art/Environment/Bonfire/fireplace_trees_BaseMap.png
  Assets/Game/Art/Environment/Bonfire/fireplace_trees_BaseMap.png.meta
  Assets/Game/Level/Prefabs/Level/Level_1/Level1_SavePoints.prefab
  Assets/Game/Level/Prefabs/Level/Level_1/Zone_Alice/Zone_Alice.prefab
  Assets/Game/Level/Prefabs/Level/Level_1/Zone_Kirill/Zone_Kirill.prefab
  Assets/Game/Level/Prefabs/Level/LocationSavePoint.prefab
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1V3.unity
Labels: ART | refactoring

#169 [AP] Implemented linked spawn zones
  Assets/Game/Level/Data/Enemies/ObjectChest_Water.asset
  Assets/Game/Level/Data/Enemies/ObjectChest_Water.asset.meta
  Assets/Game/Level/Prefabs/Enemies/Spawner/ChestSpawnPoint.prefab
  Assets/Game/Level/Prefabs/Enemies/Spawner/ChestSpawnPoint.prefab.meta
  Assets/Game/Level/Prefabs/Enemies/Spawner/EnemySpawnZoneLinked.prefab
  Assets/Game/Level/Prefabs/Enemies/Spawner/EnemySpawnZoneLinked.prefab.meta
  Assets/Game/Level/Prefabs/Enemies/Spawner/Fx.meta
  Assets/Game/Level/Prefabs/Enemies/Spawner/Fx/ChestSpawnPointEffect.prefab
  Assets/Game/Level/Prefabs/Enemies/Spawner/Fx/ChestSpawnPointEffect.prefab.meta
  Assets/Game/Level/Prefabs/Enemies/Spawner/Fx/GroundSpawnPointEffect.prefab
  Assets/Game/Level/Prefabs/Enemies/Spawner/Fx/GroundSpawnPointEffect.prefab.meta
  Assets/Game/Level/Prefabs/Enemies/Spawner/Fx/SpawnPointEffect.prefab
  Assets/Game/Level/Prefabs/Enemies/Spawner/Fx/SpawnPointEffect.prefab.meta
  Assets/Game/Level/Prefabs/Enemies/Special/Chest.meta
  Assets/Game/Level/Prefabs/Enemies/Special/Chest/ObjectChest.prefab
  Assets/Game/Level/Prefabs/Enemies/Special/Chest/ObjectChest.prefab.meta
  Assets/Game/Scripts/Enemies/EnemySpawnGroup.cs
  Assets/Game/Scripts/Enemies/EnemySpawnZone.cs
  Assets/Game/Scripts/Enemies/EnemySpawnZoneLinked.cs
  Assets/Game/Scripts/Enemies/EnemySpawnZoneLinked.cs.meta
  Assets/Game/Test/TestLocation/TestLinkedGroupsZone.prefab
  Assets/Game/Test/TestLocation/TestLinkedGroupsZone.prefab.meta
  Assets/Game/Test/TestLocation/TestLocation.unity
  Assets/Game/Test/TestLocation/TestLocation/LightingData.asset
  Assets/Game/Test/TestLocation/TestLocation/NavMesh-navmesh.asset
  Assets/Game/Test/TestLocation/TestLocation/ReflectionProbe-0.exr
Labels: DEV | refactoring, DEV | new feature

#170 [AP] Refactored AI
  Assets/Game/Level/Data/BehaviourTree/AngryEnemyAi.asset
  Assets/Game/Scripts/Actors/ActorController.cs
  Assets/Game/Scripts/Actors/Health/DamageableController.cs
  Assets/Game/Scripts/Actors/Health/DeathController.cs
  Assets/Game/Scripts/Actors/IActorController.cs
  Assets/Game/Scripts/BehaviourTree/Actions/Heal.cs
  Assets/Game/Scripts/BehaviourTree/Actions/ShoutEventIgnoreSelf.cs
  Assets/Game/Scripts/BehaviourTree/Actions/ShoutEventIgnoreSelf.cs.meta
  Assets/Game/Scripts/BehaviourTree/Conditions/StatChanged.cs
  Assets/Game/Scripts/BehaviourTree/Conditions/StatChanged.cs.meta
  Assets/Game/Scripts/Enemies/NavigationController.cs
Labels: DEV | refactoring, DEV | new feature

#173 [AP] Implemented character/object weight
  Assets/Game/Level/Data/Enemies/Objects/ObjectChest_Lava.asset
  Assets/Game/Level/Data/Enemies/Objects/ObjectChest_Life.asset
  Assets/Game/Level/Data/Enemies/Objects/ObjectChest_Revive.asset
  Assets/Game/Level/Data/Enemies/Objects/ObjectChest_Water.asset
  Assets/Game/Level/Data/Enemies/Objects/ObjectGreenCrystal.asset
  Assets/Game/Level/Prefabs/Enemies/Special/Crystal/ObjectCrystal.prefab
  Assets/Game/Scripts/Actors/MovementController.cs
  Assets/Game/Scripts/Actors/Stats/ActorStatsExtensions.cs
  Assets/Game/Scripts/Enemies/EnemyStats.cs
  Assets/Game/Scripts/Hero/HeroStats.cs
  Assets/Game/Scripts/Stats/CharacterStats.cs
  Assets/Game/Test/TestLocation/Targets/___TestTarget.asset
Labels: DEV | new feature

#176 [AS] Spawn Zones Updated
  Assets/Game/Level/Data/Enemies/M_SE_R Boss&subboss.meta
  Assets/Game/Level/Data/Enemies/M_SE_R Boss&subboss/M_D2_Bos2_Projectile.asset
  Assets/Game/Level/Data/Enemies/M_SE_R Boss&subboss/M_D2_Bos2_Projectile.asset.meta
  Assets/Game/Level/Data/Enemies/M_SE_R Boss&subboss/M_D2_Bos2_ProjectileDamage.asset
  Assets/Game/Level/Data/Enemies/M_SE_R Boss&subboss/M_D2_Bos2_ProjectileDamage.asset.meta
  Assets/Game/Level/Data/Enemies/M_SE_R Boss&subboss/M_D2_Bos2_Range.asset
  Assets/Game/Level/Data/Enemies/M_SE_R Boss&subboss/M_D2_Bos2_Range.asset.meta
  Assets/Game/Level/Data/Enemies/M_SE_m_SubBoss.asset
  Assets/Game/Level/Data/Enemies/M_SE_m_SubBoss.asset.meta
  Assets/Game/Level/Data/Enemies/M_SE_r_Boss_Earth.asset
  Assets/Game/Level/Data/Enemies/M_SE_r_Boss_Earth.asset.meta
  Assets/Game/Level/Data/Enemies/ObjectChest_Water.asset
  Assets/Game/Level/Data/Enemies/ObjectChest_Water.asset.meta
  Assets/Game/Level/Data/Enemies/Objects/ObjectChest_DashPassive.asset
  Assets/Game/Level/Data/Enemies/Objects/ObjectChest_DashPassive.asset.meta
  Assets/Game/Level/Data/Enemies/Objects/ObjectChest_Earth.asset
  Assets/Game/Level/Data/Enemies/Objects/ObjectChest_Earth.asset.meta
  Assets/Game/Level/Prefabs/Level/Level_1/Zone_Ilya/Zone_Ilya.prefab
  Assets/Game/Level/Prefabs/Level/Level_1/Zone_Kirill/Zone_Kirill.prefab
Labels: GD | refactoring

#174 [NL] Polished game level1
  Assets/Game/Level/Data/Enemies/Objects/ObjectChest_Lightning.asset
  Assets/Game/Level/Data/Enemies/Objects/ObjectChest_Lightning.asset.meta
  Assets/Game/Level/Prefabs/Enemies/M2_SN_r_Scroll_LifeTree.prefab
  Assets/Game/Level/Prefabs/Level/Level_1/Zone_Alice/Zone_Alice.prefab
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1V3.unity
Labels: GD | refactoring

#178 [AP] L1 bridges update
  Assets/Game/Art/Environment/Aqueduct/aqueduct.prefab
  Assets/Game/Level/Prefabs/Level/Level_1/Environment.meta
  Assets/Game/Level/Prefabs/Level/Level_1/Environment/Bridges.prefab
  Assets/Game/Level/Prefabs/Level/Level_1/Environment/Bridges.prefab.meta
  Assets/Game/Level/Prefabs/Level/Level_1/Level1_POI.prefab
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1V3.unity
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1V3/NavMesh-NavMeshSurfaces 1.asset
  Assets/Game/Scripts/Editor/Tools/CreateBoxCollider.cs
  Assets/Game/Scripts/Editor/Tools/CreateBoxCollider.cs.meta
  Assets/Game/Scripts/Editor/Tools/CreateEmptyParentAtCenter.cs
  Assets/Game/Scripts/Editor/Tools/CreateEmptyParentAtCenter.cs.meta
  Assets/Game/Scripts/Editor/Tools/Utils.cs
  Assets/Game/Scripts/Editor/Tools/Utils.cs.meta
Labels: DEV | refactoring, GD | refactoring

#179 [AA] Polishing UI
  Assets/Game/Level/Data/Settings/TeamsSettings.asset
  Assets/Game/Scripts/UI/MainMenu/Art/ArtView.cs
  Assets/Game/UI/Uxml/GameOver.uxml
  Assets/Game/UI/Uxml/StartScreen/ArtScreen.uxml
  Assets/Game/UI/Uxml/StartScreen/Preview.uxml
Labels: DEV | refactoring

#181 [AP] Revive fix
  Assets/Game/Scripts/GameFlow/PlanetGameplay/GameplayEntryPoint.cs
  Assets/Game/Scripts/GameFlow/PlanetGameplay/GameplayGameOver.cs
  Assets/Game/Scripts/Inventory/IInventoryRunes.cs
  Assets/Game/Scripts/Inventory/InventoryController.cs
  Assets/Game/Scripts/Inventory/Items/Runes/IReadOnlyRunes.cs
  Assets/Game/Scripts/Inventory/Items/Runes/Runes.cs
  Assets/Game/Scripts/LifetimeScopes/GameplayLifetimeScope.cs
  Assets/Game/Scripts/UI/Gameplay/Inventory/InventoryView.cs
  Assets/Game/Scripts/UI/Gameplay/Inventory/InventoryViewModel.cs
Labels: DEV | fix

#184 [AP] Small settings refactoring
  Assets/Game/Level/Prefabs/Core/RootLifetimeScope.prefab
  Assets/Game/Scripts/LifetimeScopes/RootLifetimeScope.cs
  Assets/Game/Scripts/Player/PlayerGraphicsPrefs.cs
  Assets/Game/Scripts/Settings/GameSettings.cs
  ProjectSettings/EditorSettings.asset
Labels: DEV | refactoring

#185 [NL] Corrected Runes Abilities
  Assets/Game/Level/Data/Hero/BaseAbilitites/HeroRecoveryAbility.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/Earth/HeroEarthProjectileDamage.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/Fire/HeroFireProjectileDamage.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/HeroEarthAbility.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/HeroFireAbility.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/HeroLavaAbility.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/HeroLightningAbility.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/HeroWaveAbility.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/HeroWindAbility.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/Lava/HeroLavaPuddleEffectBurnHero.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/Life/HeroLifeTree.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/Life/HeroLifeTreeRegenEffect.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/Lightning/HeroLightningProjectileEffectStun.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/Wave/HeroWave.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/Wave/HeroWaveProjectile.asset
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/L1D1_SP_Enter.asset
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/L1D2_SP_Enter.asset
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/L1D2_SP_Exit.asset
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/L1_SP_FrogIsland.asset
  Assets/Game/Level/Scenes/Levels/GameLevel/L1D1/L1D1_From_L1.asset
  Assets/Game/Level/Scenes/Levels/GameLevel/L1D1/L1D1_SP_Enter.asset
  Assets/Game/Level/Scenes/Levels/GameLevel/L1D1/L1D1_SP_Enter.asset.meta
  Assets/Game/Level/Scenes/Levels/GameLevel/L1D1/Level_1_Dung_1.unity
  Assets/Game/Level/Scenes/Levels/GameLevel/L1D2/L1D2_From_Enter.asset
  Assets/Game/Level/Scenes/Levels/GameLevel/L1D2/L1D2_From_Exit.asset
  Assets/Game/Level/Scenes/Levels/GameLevel/L1D2/L1D2_SP_Enter.asset
  Assets/Game/Level/Scenes/Levels/GameLevel/L1D2/L1D2_SP_Enter.asset.meta
  Assets/Game/Level/Scenes/Levels/GameLevel/L1D2/L1D2_SP_Exit.asset
  Assets/Game/Level/Scenes/Levels/GameLevel/L1D2/L1D2_SP_Exit.asset.meta
Labels: GD | refactoring

#186 [AP] Added MP regeneration to Life Tree
  Assets/Game/Level/Data/Common/Status/StatusRegen.asset
  Assets/Game/Level/Data/Common/Status/StatusRegenHp.asset
  Assets/Game/Level/Data/Common/Status/StatusRegenHp.asset.meta
  Assets/Game/Level/Data/Common/Status/StatusRegenMp.asset
  Assets/Game/Level/Data/Common/Status/StatusRegenMp.asset.meta
  Assets/Game/Level/Data/Hero/RuneAbilities/Life/HeroLifeTreeEffects.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/Life/HeroLifeTreeRegenEffect.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/Life/HeroLifeTreeRegenHpEffect.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/Life/HeroLifeTreeRegenHpEffect.asset.meta
  Assets/Game/Level/Data/Hero/RuneAbilities/Life/HeroLifeTreeRegenMpEffect.asset
  Assets/Game/Level/Data/Hero/RuneAbilities/Life/HeroLifeTreeRegenMpEffect.asset.meta
Labels: GD | new feature

#189 [AP] Credits update
  Assets/Game/Level/Data/Localization/ImportedSheets/Localization - Dialog.csv
  Assets/Game/Level/Data/Localization/Tables/Dialog/Dialog Shared Data.asset
  Assets/Game/Level/Data/Localization/Tables/Dialog/Dialog_be.asset
  Assets/Game/Level/Data/Localization/Tables/Dialog/Dialog_en.asset
  Assets/Game/Level/Data/Localization/Tables/Dialog/Dialog_ru.asset
  Assets/Game/Level/Data/Localization/Tables/Dialog/Dialog_uk.asset
  Assets/Game/Level/Data/Settings/UISettings.asset
  Assets/Game/Scripts/UI/Constants/LayoutNames.cs
  Assets/Game/Scripts/UI/Credits/CreditsView.cs
  Assets/Game/UI/Uss/CreditsStyle.uss
  Assets/Game/UI/Uss/CreditsStyle.uss.meta
  Assets/Game/UI/Uss/CutsceneStyle.uss
  Assets/Game/UI/Uxml/Credits/CreditsMember.uxml
  Assets/Game/UI/Uxml/Credits/CreditsScreen.uxml
  Assets/Game/UI/Uxml/Credits/CreditsTeam.uxml
Labels: DEV | refactoring

#190 [AP] Mushrooms down
  Assets/Game/Level/Prefabs/Level/Level_1/Environment/Level1_Bridges.prefab
  Assets/Game/Level/Prefabs/Level/Level_1/Level1_Doors.prefab
  Assets/Game/Level/Prefabs/Level/Level_1/Zone_Alice/Zone_Alice.prefab
  Assets/Game/Level/Prefabs/Level/Level_1/Zone_Ilya/Zone_Ilya.prefab
  Assets/Game/Level/Prefabs/Level/Level_1/Zone_Kirill/Zone_Kirill.prefab
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1 1.asset
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1V3.unity
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1V3/NavMesh-NavMeshSurfaces 1.asset
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1V3/OcclusionCullingData.asset
Labels: GD | refactoring, ART | refactoring

#191 [AP] Fixes UI, L1 obstacles and localization
  Assembly-CSharp.csproj.DotSettings
  Assets/Forest Ruins Pack Cute Series/Prefabs/Urns/Urn 01.prefab
  Assets/Forest Ruins Pack Cute Series/Prefabs/Urns/Urn 03.prefab
  Assets/Game/Level/Data/Localization/ImportedSheets/Localization - GUI.csv
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI Shared Data.asset
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI_be.asset
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI_en.asset
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI_ru.asset
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI_uk.asset
  Assets/Game/Level/Data/Settings/UISettings.asset
  Assets/Game/Level/Prefabs/UI/Gameplay/GameplayUI.prefab
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1V3.unity
  Assets/Game/Level/Scenes/Levels/GameLevel/L1/Level_1V3/NavMesh-NavMeshSurfaces 1.asset
  Assets/Game/Scripts/Input/GameInputControls.cs
  Assets/Game/Scripts/Localization/ILocalizationService.cs
  Assets/Game/Scripts/Localization/UnityLocalization.cs
  Assets/Game/Scripts/Player/PlayerLocalizationPrefs.cs
  Assets/Game/Scripts/UI/Gameplay/GameOver/GameOverView.cs
  Assets/Game/Scripts/UI/Gameplay/Pause/PauseView.cs
  Assets/Game/Scripts/UI/Modal/ModalView.cs
  Assets/Game/Scripts/UI/Settings/SettingsView.cs
  Assets/Game/Scripts/UI/Settings/SettingsViewModel.cs
  Assets/Game/Scripts/Utils/StringExtensions.cs
  Assets/Game/Scripts/Utils/StringExtensions.cs.meta
  Assets/Game/Settings/Input/GameInputControls.inputactions
  Assets/Game/Settings/Input/InputSystem.inputsettings.asset
  Assets/Game/UI/Fonts/koliko-Regular SDF.asset
  Assets/Game/UI/Uss/Common.uss
  Assets/Game/UI/Uss/ModalScreenStyle.uss
Labels: DEV | fix, DEV | refactoring, GD | refactoring

#194 [AP] Level up (1.0.0rc1)
  Assets/Game/Level/Prefabs/UI/Gameplay/GameplayUI.prefab
  ProjectSettings/ProjectSettings.asset
Labels: New Version

#195 [AP] Steam integration
  Assets/Game/Level/Data/Settings/AchievementsSettings.asset
  Assets/Game/Level/Data/Settings/AchievementsSettings.asset.meta
  Assets/Game/Level/Data/Settings/GameSettings.asset
  Assets/Game/Level/Prefabs/Core/RootLifetimeScope.prefab
  Assets/Game/Scripts/Achievements.meta
  Assets/Game/Scripts/Achievements/AchievementsSettings.cs
  Assets/Game/Scripts/Achievements/AchievementsSettings.cs.meta
  Assets/Game/Scripts/Achievements/GameAchievements.cs
  Assets/Game/Scripts/Achievements/GameAchievements.cs.meta
  Assets/Game/Scripts/Achievements/GameStats.cs
  Assets/Game/Scripts/Achievements/GameStats.cs.meta
  Assets/Game/Scripts/Achievements/IAchievementsService.cs
  Assets/Game/Scripts/Achievements/IAchievementsService.cs.meta
  Assets/Game/Scripts/Achievements/IGameStatsService.cs
  Assets/Game/Scripts/Achievements/IGameStatsService.cs.meta
  Assets/Game/Scripts/Achievements/InventoryAchievementsHandler.cs
  Assets/Game/Scripts/Achievements/InventoryAchievementsHandler.cs.meta
  Assets/Game/Scripts/Achievements/PlaceholderAchievements.cs
  Assets/Game/Scripts/Achievements/PlaceholderAchievements.cs.meta
  Assets/Game/Scripts/Achievements/PlaceholderStats.cs
  Assets/Game/Scripts/Achievements/PlaceholderStats.cs.meta
  Assets/Game/Scripts/Achievements/RuneAchievementsSettings.cs
  Assets/Game/Scripts/Achievements/RuneAchievementsSettings.cs.meta
  Assets/Game/Scripts/Editor/Steam.meta
  Assets/Game/Scripts/Editor/Steam/ClearAchievements.cs
  Assets/Game/Scripts/Editor/Steam/ClearAchievements.cs.meta
  Assets/Game/Scripts/GameFlow/PlanetGameplay/PlanetGameOverState.cs
  Assets/Game/Scripts/GameFlow/Root/CompleteGameState.cs
  Assets/Game/Scripts/GameFlow/Root/IntroState.cs
  Assets/Game/Scripts/Inventory/IInventoryItems.cs
  Assets/Game/Scripts/Inventory/InventoryController.cs
  Assets/Game/Scripts/LifetimeScopes/GameplayLifetimeScope.cs
  Assets/Game/Scripts/LifetimeScopes/RootLifetimeScope.cs
  Assets/Game/Scripts/Persistence/LocalPersistence.cs
  Assets/Game/Scripts/Steam.meta
  Assets/Game/Scripts/Steam/SteamAchievements.cs
  Assets/Game/Scripts/Steam/SteamAchievements.cs.meta
  Assets/Game/Scripts/Steam/SteamOverlay.cs
  Assets/Game/Scripts/Steam/SteamOverlay.cs.meta
  Assets/Game/Scripts/Steam/SteamPersistence.cs
  Assets/Game/Scripts/Steam/SteamPersistence.cs.meta
  Assets/Game/Scripts/Steam/SteamService.cs
  Assets/Game/Scripts/Steam/SteamService.cs.meta
  Assets/Game/Scripts/Steam/SteamStats.cs
  Assets/Game/Scripts/Steam/SteamStats.cs.meta
  Assets/Plugins/FMOD/platforms/win/lib/x86_64/fmodstudioL.dll.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectSettings.asset
  debug.log
  steam_appid.txt
Labels: DEV | refactoring, DEV | new feature

#197 [AP] Localization fix
  Assets/Game/Level/Data/Localization/ImportedSheets/Localization - Dialog.csv
  Assets/Game/Level/Data/Localization/ImportedSheets/Localization - GUI.csv
  Assets/Game/Level/Data/Localization/Tables/Dialog/Dialog_uk.asset
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI_be.asset
  Assets/Game/Level/Data/Localization/Tables/GUI/GUI_uk.asset
  Assets/Game/UI/Fonts/OTF.meta
  Assets/Game/UI/Fonts/OTF/borsok SDF.asset
  Assets/Game/UI/Fonts/OTF/borsok SDF.asset.meta
  Assets/Game/UI/Fonts/OTF/borsok.otf
  Assets/Game/UI/Fonts/OTF/borsok.otf.meta
  Assets/Game/UI/Fonts/borsok SDF-Cyrillic.asset
  Assets/Game/UI/Fonts/borsok SDF-Cyrillic.asset.meta
  Assets/Game/UI/Fonts/borsok SDF.asset
  Assets/Game/UI/Fonts/koliko-Bold SDF.asset
  Assets/Game/UI/Fonts/koliko-Regular SDF.asset
Labels: ART | refactoring
